(function(){if(!google.nocsixjs&&google.timers&&google.timers.load.t)google.timers.load.t.xjses=(new Date).getTime();})();
(function(){var e={};google.med=function(a){if(google.mc){for(var b=0,f=google.mc.length;b<f;b++){var c=a=="dispose"?f-b-1:b;try{var d=e[google.mc[c][0]];d&&d[a]&&d[a](google.mc[c][1])}catch(g){google.ml(g,false,{cause:"m"+a,index:c,mid:google.mc[c]&&google.mc[c][0]})}}if(a=="dispose")google.mc=null}};google.register=function(a,b){e[a]=b};})();
(function(){var h=true,i=false;google.browser={};google.browser.engine={IE:i,GECKO:i,WEBKIT:i,OPERA:i};google.browser.product={IE:i,FIREFOX:i,SAFARI:i,IPAD:i,CHROME:i,OPERA:i};google.browser.engine.version="";google.browser.product.version="";
google.browser.init=function(a){var b=null,c=null;if(window.opera){google.browser.engine.OPERA=h;google.browser.product.OPERA=h;b=c=/Opera\/(\S+)/}else if(a.indexOf("MSIE")!=-1){google.browser.engine.IE=h;google.browser.product.IE=h;b=c=/MSIE\s+([^\);]+)(\)|;)/}else if(a.indexOf("WebKit")!=-1){google.browser.engine.WEBKIT=h;if(a.indexOf("Chrome")!=-1){google.browser.product.CHROME=h;c=/Chrome\/(\S+)/}else if(a.indexOf("iPad")!=-1){google.browser.product.IPAD=h;c=/Version\/(\S+)/}else if(a.indexOf("Safari")!=
-1){google.browser.product.SAFARI=h;c=/Version\/(\S+)/}b=/WebKit\/(\S+)/}else if(a.indexOf("Gecko")!=-1){google.browser.engine.GECKO=h;if(a.indexOf("Firefox")!=-1){google.browser.product.FIREFOX=h;c=/Firefox\/(\S+)/}b=/rv\:([^\);]+)(\)|;)/}if(b){b=b.exec(a);google.browser.engine.version=b?b[1]:""}if(c){b=c.exec(a);google.browser.product.version=b?b[1]:""}};google.browser.init(window.navigator.userAgent);
google.browser.compareVersions=function(a,b){function c(q,r){if(q<r)return-1;else if(q>r)return 1;return 0}for(var d=0,e=a.replace(/^\s+|\s+$/g,"").split("."),f=b.replace(/^\s+|\s+$/g,"").split("."),g=Math.max(e.length,f.length),j=0;d==0&&j<g;j++){var o=e[j]||"",k=f[j]||"",p=RegExp("(\\d*)(\\D*)","g"),s=RegExp("(\\d*)(\\D*)","g");do{var m=p.exec(o)||["","",""],n=s.exec(k)||["","",""];if(m[0].length==0&&n[0].length==0)break;d=m[1].length==0?0:parseInt(m[1],10);var t=n[1].length==0?0:parseInt(n[1],
10);d=c(d,t)||c(m[2].length==0,n[2].length==0)||c(m[2],n[2])}while(d==0)}return d};google.browser.isEngineVersion=function(a){return google.browser.compareVersions(google.browser.engine.version,a)>=0};google.browser.isProductVersion=function(a){return google.browser.compareVersions(google.browser.product.version,a)>=0};google.style=google.style||{};google.style.hasClass=function(a,b){if(!a||!b)return i;return RegExp("(^|\\s)"+b+"($|\\s)").test(a.className)};google.style.addClass=function(a,b){if(a&&b&&!google.style.hasClass(a,b)){var c=a.className==""?[]:a.className.split(/\s/);c.push(b);a.className=c.join(" ")}};google.style.removeClass=function(a,b){if(google.style.hasClass(a,b)){for(var c=a.className.split(/\s/),d=c.length-1;d>=0;d--)c[d]==b&&c.splice(d,1);a.className=c.join(" ")}};google.dom={};google.dom.g=/^(\w+)?(?:\.(.+))?$/;google.dom.h=/^#([\w-]+)$/;google.dom.append=function(a){return(document.getElementById("xjsc")||document.body).appendChild(a)};google.dom.create=function(a,b){var c=a.match(google.dom.g),d=document.createElement(c[1]);if(c[2])d.className=c[2];if(b)d.innerHTML=b;return d};
google.dom.get=function(a,b,c){var d;if(d=a.match(google.dom.h)){a=document.getElementById(d[1]);if(c)return a?[a]:[];return a}else{d=a.match(google.dom.g);a=d[2]&&RegExp("\\b"+d[2]+"\\b");b=(b||document).getElementsByTagName(d[1]||"*");if(a){d=b;b=[];for(var e=0,f;f=d[e++];)a.test(f.className)&&b.push(f)}}return b.length>1||c?b:b[0]};google.dom.insert=function(a,b,c){return b.parentNode.insertBefore(a,c?b.nextSibling:b)};google.dom.remove=function(a){return a&&a.parentNode&&a.parentNode.removeChild(a)};
google.dom.set=function(a){for(var b=1;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1],e=a.style;if(e&&c in e)e[c]=d;else if(c in a)a[c]=d;else if(google.browser.engine.IE&&e&&c=="opacity"){a.zoom=1;e.filter=(e.filter||"").replace(/alpha\([^)]*\)/,"")+"alpha(opacity="+d*100+")"}}return a};google.listen=function(a,b,c){a.addEventListener?a.addEventListener(b,c,i):a.attachEvent("on"+b,c)};google.unlisten=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,i):a.detachEvent("on"+b,c)};google.msg={};google.msg.b={};google.msg.listen=function(){for(var a=0;a<arguments.length-1;a+=2){var b=arguments[a];google.msg.b[b]||(google.msg.b[b]=[]);google.msg.b[b].push(arguments[a+1])}};google.msg.unlisten=function(){for(var a=0;a<arguments.length-1;a+=2){var b=arguments[a];if(b=google.msg.b[b])for(var c=arguments[a+1],d=0;d<b.length;++d)if(b[d]==c){b.splice(d,1);break}}};
google.msg.send=function(a,b,c,d){var e=c===undefined?h:c,f=c===i,g=b&&b[0]===c;if(a in google.msg.b){if(d===undefined)d=i;var j;j=typeof d=="function"?d:function(p){return p===d};for(var o=0,k;k=google.msg.b[a][o++];){k=k.apply(this,b||[]);if(f)e=e||k;else{if(g)b[0]=k;e=k;if(j(e))return e}}}if(typeof d=="function")return c;return e};google.nav=function(a,b){google.nav.e(a,b)};google.nav.a=function(){return window.location};google.nav.j=location.protocol+"//"+location.host;google.nav.go=function(a,b,c){google.msg.send(32,[a,b,c],i)||google.nav.e(a,b)};google.nav.gom=1;
google.nav.e=function(a,b){try{if(RegExp("^("+google.nav.j+")?/(url|aclk)\\?.*&rct=j(&|$)").test(a))if(b){google.r=1;b.location.replace(a)}else{if(!google.nav.c){google.nav.c=document.createElement("iframe");google.nav.c.style.display="none";google.dom.append(google.nav.c)}google.r=1;google.nav.c.src=a}else google.nav.a().href=a}catch(c){google.nav.a().href=a}};
google.nav.search=function(a,b){var c=google.nav.a().search.match(/[?&][\w\.\-~]+=([^&]*)/g),d={};if(c)for(var e=0,f;f=c[e++];){var g=f.match(/([\w\.\-~]+?)=(.*)/);f=g[1];g=g[2];d[f]=g}for(f in a)if(a.hasOwnProperty(f))d[f]=a[f];c=["/search?"];e=h;for(f in d)if(d.hasOwnProperty(f)){c.push((e?"":"&")+f+"="+d[f]);e=i}google.nav.go(c.join(""),undefined,b)};google.nav.getLocation=function(){return google.nav.a().pathname+google.nav.a().search};
google.nav.getLocationHash=function(){var a=google.nav.a();return a.hash?a.href.substr(a.href.indexOf("#")):""};google.nav.getParam=function(a){var b=google.nav.getLocationHash().match("[#?&]"+a+"=([^&]*)");if(b)return b[1];if(b=google.nav.a().search.match("[?&]"+a+"=([^&]*)"))return b[1];return null};google.nav.getQuery=function(){return google.nav.getParam("q")};google.util={};var l=["&","&amp;","<","&lt;",">","&gt;",'"',"&quot;","'","&#39;","{","&#123;"];google.util.escape=function(a){for(var b=0;b<l.length;b+=2)a=a.replace(RegExp(l[b],"g"),l[b+1]);return a};google.util.unescape=function(a){for(var b=0;b<l.length;b+=2)a=a.replace(RegExp(l[b+1],"g"),l[b]);return a};google.util.eventTarget=function(a){return google.browser.engine.IE?window.event.srcElement:a.target};
google.util.stopPropagation=function(a){if(a)a.stopPropagation&&a.stopPropagation();else window.event.cancelBubble=h};google.util.getSelection=function(){return window.getSelection&&window.getSelection().toString()||document.selection&&document.selection.createRange&&document.selection.createRange().text};google.srp={};google.srp.d=function(a,b,c){var d=RegExp("([?&])"+b+"=.*?(&|$)");a=a.replace(/^([^#]*)(#|$)/,function(e,f){return f});if(!a.match(d)&&c!="")return a+"&"+b+"="+c;return a.replace(d,function(e,f,g){return c?f+b+"="+c+g:g?f:""})};google.srp.isSerpLink=function(a){return/(search|images)/.test(a.href)};google.srp.isSerpForm=function(a){return/\/search$/.test(a.action)};
google.srp.updateLinksWithParam=function(a,b,c,d){var e=document.getElementsByTagName("A");google.base_href=google.srp.d(google.base_href,a,b);for(var f=0,g;g=e[f++];)if(c(g)){var j=google.browser.engine.IE?g.innerHTML:undefined;g.href=google.srp.d(g.href,a,b);if(j!=undefined)g.innerHTML=j}for(f=0;c=document.forms[f++];)if(d(c)){for(g=e=0;j=c.elements[g++];)if(j.name==a){e=1;if(b!="")j.value=b;else j.parentNode.removeChild(j)}if(!e&&b!=""){e=document.createElement("input");e.type="hidden";e.value=
b;e.name=a;c.appendChild(e)}}};google.srp.qs=function(a){if(a=google.util.eventTarget(a)){for(;!google.style.hasClass(a,"qs");){a=a.parentNode;if(!a||a==document.body)return}var b=document.getElementsByName("q"),c=b&&b[0];b=document.getElementById("tsf-oq");if(c&&b&&window.encodeURIComponent){c=c.value;b=google.browser.engine.GECKO?b.textContent:b.innerText;if(c&&c!=b){b=google.srp.d(a.href,"q",encodeURIComponent(c));a.href=google.srp.d(b,"prmd","")}}}};google.style=google.style||{};google.style.i=0;
google.style.getComputedStyle=function(a,b,c){var d=c?"":0;var e=document.defaultView&&document.defaultView.getComputedStyle(a,"");try{d=e.getPropertyValue(b);d=c?d:parseInt(d,10)}catch(f){}return d};google.style.getHeight=function(a){var b=google.style.getComputedStyle(a,"height");return isNaN(b)?0:b};
google.style.getWidth=function(a){var b=google.style.getComputedStyle(a,"width");return isNaN(b)?0:b};
google.style.getPageOffsetTop=function(a){return a.offsetTop+(a.offsetParent?google.style.getPageOffsetTop(a.offsetParent):0)};google.style.getPageOffsetLeft=function(a){return a.offsetLeft+(a.offsetParent?google.style.getPageOffsetLeft(a.offsetParent):0)};google.style.getPageOffsetStart=function(a){return google.style.getPageOffsetLeft(a)+google.style.i?google.style.getWidth(a):0};google.style.getColor=function(a){return google.style.getComputedStyle(a,"color",h)};google.xhr=function(){var a=null;if(window.XMLHttpRequest)try{a=new XMLHttpRequest}catch(b){}if(!a)for(var c=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],d=0,e;e=c[d++];)try{a=new ActiveXObject(e);break}catch(f){}return a};google.isOpera=i;google.isIE=i;google.isSafari=i;
google.getHeight=function(a){return google.style.getHeight(a)};google.getWidth=function(a){return google.style.getWidth(a)};google.getComputedStyle=function(a,b,c){return google.style.getComputedStyle(a,b,c)};google.getPageOffsetTop=function(a){return google.style.getPageOffsetTop(a)};google.getPageOffsetLeft=function(a){return google.style.getPageOffsetLeft(a)};google.getPageOffsetStart=function(a){return google.style.getPageOffsetStart(a)};
google.hasClass=function(a,b){return google.style.hasClass(a,b)};google.getColor=function(a){return google.style.getColor(a)};google.append=function(a){return google.dom.append(a)};google.rhs=function(){};google.eventTarget=function(a){return a.target;};google.bind=function(a,b,c){google.listen(a,b,c)};
google.unbind=function(a,b,c){google.unlisten(a,b,c)};})();
(function(){google.History={};var c=[],g="/";google.History.client=function(a){c.push(a);return c.length-1};var h,i;function j(){var a=h.value;i=a?eval("("+a+")"):{}}function k(a,b){j();i[g]||(i[g]={});i[g][a]=b;h.value=google.stringify(i)}var l=[];function m(){for(var a=0,b;b=l[a++];)b();l=[]}google.History.addPostInitCallback=function(a){l.push(a)};google.History.save=function(a,b){h&&k(a,b)};
google.History.initialize=function(a){g=a;i=null;if(h=document.getElementById("hcache")){j();for(a=0;a<c.length;++a)i&&i[g]&&i[g][a]&&c[a].call(null,i[g][a]);m()}};var n=n||{};n.json={};n.DEBUG=true;n.LOCALE="en";
n.typeOf=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b};n.isArray=function(a){return n.typeOf(a)=="array"};n.json.j=function(a){if(/^\s*$/.test(a))return false;var b=/\\["\\\/bfnrtu]/g,f=/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e=/^[\],:{}\s\u2028\u2029]*$/;return e.test(a.replace(b,"@").replace(f,"]").replace(d,""))};
n.json.parse=function(a){a=String(a);if(n.json.j(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};n.json.unsafeParse=function(a){return eval("("+a+")")};n.json.a=function(a){return(new n.json.Serializer).a(a)};n.json.Serializer=function(){};n.json.Serializer.prototype.a=function(a){var b=[];this.b(a,b);return b.join("")};
n.json.Serializer.prototype.b=function(a,b){switch(typeof a){case "string":this.d(a,b);break;case "number":this.g(a,b);break;case "boolean":b.push(a);break;case "undefined":b.push("null");break;case "object":if(a==null){b.push("null");break}if(n.isArray(a)){this.e(a,b);break}this.h(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};n.json.Serializer.c={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"};
n.json.Serializer.i=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;n.json.Serializer.prototype.d=function(a,b){b.push('"',a.replace(n.json.Serializer.i,function(f){if(f in n.json.Serializer.c)return n.json.Serializer.c[f];var d=f.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return n.json.Serializer.c[f]=e+d.toString(16)}),'"')};n.json.Serializer.prototype.g=function(a,b){b.push(isFinite(a)&&!isNaN(a)?a:"null")};
n.json.Serializer.prototype.e=function(a,b){var f=a.length;b.push("[");for(var d="",e=0;e<f;e++){b.push(d);this.b(a[e],b);d=","}b.push("]")};n.json.Serializer.prototype.h=function(a,b){b.push("{");var f="",d;for(d in a)if(a.hasOwnProperty(d)){var e=a[d];if(typeof e!="function"){b.push(f);this.d(d,b);b.push(":");this.b(e,b);f=","}}b.push("}")};window.google.stringify=n.json.a;if(window.JSON&&window.JSON.stringify&&navigator.userAgent.indexOf("Chrome")==-1)window.google.stringify=window.JSON.stringify;})();
(function(){var a,b;google.rhs=function(){if(!google.drhs)if(document.getElementById("mbEnd")&&(a||b)){var d=google.getHeight(document.getElementById("rhsline")),c=a?google.getHeight(a):0;if(b)c+=google.getHeight(b)+18;document.getElementById("rhspad").style.height=c>d?Math.min(9999,c-d)+"px":google.isIE?"":0}};function e(){a=document.getElementById("tads");b=document.getElementById("3po");google.rhs()}e();google.listen(window,"resize",google.rhs);google.rein.push(e);})();
(function(){var f=0,h=[];function i(b){return b}
function k(){for(var b=0,c;c=h[b++];){c=c;var g=google.time()-c.e;if(g>=c.c||c.a){for(var e=0,a=void 0;a=c.d[e++];)google.dom.set(a[0],a[1],a[6]?"rgb("+a[3].join(",")+")":a[3]+a[5]);c.a=true;c.b&&c.b();c=0}else{for(e=0;a=c.d[e++];){var d=a[4](g/c.c);d=a[6]?"rgb("+[l(a[2][0],a[3][0],d,true),l(a[2][1],a[3][1],d,true),l(a[2][2],a[3][2],d,true)].join(",")+")":l(a[2],a[3],d,a[5]=="px");google.dom.set(a[0],a[1],d+a[5])}c=1}c||h.splice(--b,1)}if(!h.length){window.clearInterval(f);f=0}}
function l(b,c,g,e){b=b+(c-b)*g;return e?Math.round(b):b}function m(b){b=b.match(/#(..)(..)(..)/).slice(1);for(var c=0;c<3;++c)b[c]=parseInt(b[c],16);return b}google.dstr.push(function(){window.clearInterval(f);f=0;h=[]});google.fx={};google.fx.linear=i;google.fx.easeOut=function(b){return 1-Math.pow(1-b,3)};google.fx.easeInAndOut=function(b){return(3-2*b)*b*b};
google.fx.animate=function(b,c,g){for(var e=0,a;a=c[e++];){var d=typeof a[2]=="string";if(d){a[2]=m(a[2]);a[3]=m(a[3]);a[5]=""}else a[5]=a[5]==null?"px":a[5];a[4]=a[4]||i;a[6]=d;google.dom.set(a[0],a[1],d?"rgb("+a[2].join(",")+")":a[2]+a[5])}var j={c:b,b:g,e:google.time(),d:c};h.push(j);f=f||window.setInterval(k,15);return{finish:function(){if(!j.a){j.a=true;k()}}}};google.fx.wrap=function(b){var c=document.createElement("div");b.parentNode.replaceChild(c,b);c.appendChild(b);return c};
google.fx.unwrap=function(b){b.parentNode.parentNode.replaceChild(b,b.parentNode)};})();
(function(){google.event=google.event||{};google.event.back={};var c=[],f=[],g={a:false,kEI:-1};function h(){google.History.save(i,g)}function k(){for(var b=[],d=0,a=c.length;d<a;d++){var e=c[d](g[f[d]]);if(e){b.length>0&&b.push(",");b.push(e)}}b.push("&ei=",google.kEI);window.google.log("backbutton",b.join(""))}function l(b,d){return function(a){a=a||window.event;for(a=a.target||a.srcElement;a.parentNode&&a.tagName!="A";)a=a.parentNode;b(a,d?g[d]:null);d&&h()}}
function m(){if(!g.a){g.a=true;g.kEI=google.kEI;h();if(window.addEventListener){window.addEventListener("pageshow",n,false);o=false}}}var p=google.j&&google.j.en,o;function n(b){if((b.a||o)&&!p)k();o=true}var i=google.History.client(function(b){g=b;g.a&&google.kEI==g.kEI&&k()});function q(){c.length=0;f.length=0}google.dstr&&google.dstr.push(q);
google.event.back.register=function(b,d,a,e){if(e)g[e]={};for(var r=document.getElementsByTagName("a"),s=0,j;j=r[s++];)b(j)&&google.listen(j,"click",l(d,e));c.push(a);f.push(e)};google.event.back.init=function(){g={a:false,kEI:-1};google.History.addPostInitCallback(m)};google.event.back.saveHistory=h;})();
(function(){var g=true,i=null,j=false,l;window.google||(window.google={});var m=0,o=0;if(google.browser.engine.IE)o=document.documentMode?document.documentMode:parseInt(google.browser.engine.version.split(".")[0],10);var t={0:google.browser.engine.WEBKIT,1:!google.browser.engine.IE,2:g,3:g,4:g},w={0:g,1:g,2:j,3:g,4:j},x=[0,1,2,3,4],y={},z={},A={},B=function(a,b,c){this.Ba=a;this.j=b;this.Aa=c},C={},D=function(a){this.Ra=a;this.C={};this.P={}};
D.prototype.Ea=function(a,b,c){this.C[a]=c;if(typeof this.P[b]=="number")this.P[b]++;else this.P[b]=1};D.prototype.wa=function(a,b){a&&delete this.C[a];b&&this.P[b]--};D.prototype.pa=function(a){return this.C[a]};D.prototype.Ja=function(a,b){if(this.P[a]>0)for(var c in this.C){var d=this.C[c].j;if(d&&d.length>1)if(a==b(d[0].u,this.Ra))return this.C[c]}return i};
var E={},F=/[&\?]ech=([0-9]+)/,aa=/[\?&#](tch|ech|psi|wrapid)=[^&]*/g,ba=function(a,b,c,d,e,f){this[5]=a;this[2]=b;this[4]=c;this[3]=d;this[0]=e;this[1]=f},ca=function(a,b,c,d){this.noWrapper=a;this.name=b;this.avgTimingThresholds=c;this.maxTimingThresholds=d};
window.google.gtr=function(a,b){var c;c=a;var d=[];if(c)for(f=0;f<c.length;f++){var e=c[f];h=e[5];if(typeof h!="undefined"&&t[h])if(h!=0||e[4])d.push(e)}else for(var f=0;f<x.length;++f){var h=x[f];t[h]&&h!=0&&d.push(new ba(h,g))}c=d;if(!c.length)return i;d=b||new ca;return new G(c,d)};
var da=function(a){return a.substring(a.indexOf("?")+1).split("&").sort().join("&")},ea=function(a){a=a.replace(/^http[s]?:\/\/[^\/]*/,"");var b=a.indexOf("?");return b==-1?a:a.substring(0,b)},fa=function(a){if(!a)return a;return a.replace(aa,"")},I=function(a,b,c){try{return google.browser.engine.IE?eval("("+a+")"):(new Function("return "+a))()}catch(d){H(1,9,b,d,c)}return a},M=function(a,b){a.v=b[4];a.ta=!b[2];a.o=b[3];a.ja=b[5];a.I=b[0];a.O=b[1]},G=function(a,b){M(this,a[0]);this.b=b.noWrapper;
this.La=b.name;this.K=function(){};this._ckf(da);this.R={};this.ca=ea;this.oa=59;this.Pa=a.splice(1,a.length-1);this.r=[];this.L={};this.A=g;this.da={};this.Q=[0,0,0];this.V=[0,0,0];this.N=j;this.ga={};this.s=new N;this.Qa=google.kEI+google.time();this.ya=0;this._stt(b.avgTimingThresholds,b.maxTimingThresholds)},O=function(a,b,c,d,e,f){if(a==0||a==1){e=e;d={_svty:a,_err:b,_type:d&&d.M(),_noWrap:d&&d.b};if(f)d._data=encodeURIComponent(""+f);try{d._wl=encodeURIComponent(google.nav.getLocation())}catch(h){}google.ml(e||
Error("comm"),j,d)}for(d=0;e=c[d++];)e.la(a,b,f)};
G.prototype._o=function(){if(!this.a){switch(this.ja){case 0:if(this.ta&&y[this.v]&&!this.b){this.a=y[this.v];this.a.J(this);this.a.fa++;this.A=j;return g}else this.a=new P(this.v,this.b);break;case 1:this.a=new Q(g,this.b,this.I,this.O);break;case 2:this.a=new Q(j,this.b,this.I,this.O);break;case 3:this.a=new R(this.La,this.b,this.o);break;case 4:this.a=new S(this.b,this.I,this.O);break;default:O(0,18,this.r,this.a);return j}var a=!this.a;if(this.a){this.a.J(this);a=!this.a.open()}if(a){this.a=i;
a=this.Pa.shift();if(!a)return j;M(this,a);return this._o()}else if(this.ta)if(this.ja==0)y[this.v]=this.a}this.A=j;return g};var T=function(a){if(a.j&&a.j.length>0){var b=google.time();if(a.Ba+a.Aa*1E3<b)a.j=[]}},ga=function(a,b,c,d,e){this.d=a;this.e=b;this.u=c;this.c=d;this.ct=e};
G.prototype._d=function(a,b,c,d){if(!this.A){var e=d!==undefined;if(typeof a=="string")a=new ga(a);var f=a.c&&a.c==1;if(typeof c!="undefined"&&this.b)f=c;var h=a.u?this.ca(a.u):"",k=a.e,p=E[h],s=C[h],v=fa(a.u)||"",n;if(typeof a.d!="undefined"&&a.d!=i){c=this.L[h]||this.L.unknown||[];var q=a.u?a.u.match(F):0;if(q){n=this.ga[q[1]];var r=this.da[q[1]];if(r){c.unshift(r);if(!a.c||a.c==0)delete this.da[q[1]]}if(!e)if(n){r=google.time()-n;f?this.s.Ta(q[1],r):this.s.Ua(q[1],r)}}if(!c.length){O(1,10,this.r,
this.a,i,h);return}var ha=this;r=google.time();for(var ja=function(){var J=[],u=p&&p.pa(k);if(!u){u=ha.K(v,h);u=s&&s[u]}if(h&&u)for(var ia=!e?u.j.length:Math.min(u.j.length,d),K=0;K<ia;++K)J.push(u.j[K].d);J.push(a.d);return J.join("")},L=0;L<c.length;++L)c[L].la(a.d,ja,v,f,e,n);if(!e&&q){this.s.Sa(q[1],google.time()-r);if(!f&&this.N)(n=this.s.Ha(this.Q,this.V))&&O(2,15,this.r,this.a,i,n.join(","))}}if(a.u&&!b){b=this.K(v,h);if(!C[h]){E[h]=p=new D(h);C[h]={}}s=C[h];if(a.c==-1){p&&p.wa(k,b);delete s[b]}else if(typeof a.d!=
"undefined"&&a.d!=i){n=p&&p.pa(k);c=j;if(n)T(n);else{c=g;n=new B(0,[],0)}q=google.time();n.Ba=q;q=a.ct||this.oa;n.Aa=q;n.j.push(a);if(f)if(k)c&&p&&p.Ea(k,b,n);else O(1,8,this.r,this.a);else{s[b]=n;p&&p.wa(k,b)}}}}};
var U=i,ka=function(a){if(window.postMessage){if(!U){U=[];var b=function(c){if(c&&c.source==window&&c.data=="com.brb"){U.length&&U.shift()();U.length&&window.postMessage("com.brb",window.location.href)}};google.listen(window,"message",b)}U.push(a);window.postMessage("com.brb",window.location.href)}else window.setTimeout(a,0)};
G.prototype._s=function(a,b,c){if(this.A){O(0,14,this.r,this.a);return j}if(!b){var d=this.qa(a);if(d&&d.j.length>0){b=d.j[0];if(b=b.u&&b.u.match(F))this.ga[b[1]]=google.time();var e=this;for(b=0;b<d.j.length;++b)(function(f,h,k){ka(function(){e._d(f,g,h,k)})})(d.j[b],b<d.j.length-1,b);return g}}d=a.indexOf("?")==-1?"?":"&";a=[a,d];if(!this.b){a.push("tch=");a.push(this._t())}if(!this.a.za)this.a.za=1;d=this.a.za++;a.push("&ech=",d);a.push("&psi=",this.Qa+this.ya);if(c)this.da[d]=c;a=a.join("");this.ga[d]=
google.time();this.a.$(a,b);return g};G.prototype._ckf=function(a,b){if(b){this.R[b]&&O(2,4,this.r,this.a,i,b);this.R[b]=a}else{var c=this;this.K=function(d,e){return c.R[e]?c.R[e](d):a(d)}}};G.prototype._dtf=function(a){this.ca=a};G.prototype._sct=function(a){this.oa=a};G.prototype._stt=function(a,b){this.Q=a||[0,0,0];this.V=b||[0,0,0];this.N=j;for(var c=0;c<this.Q.length;++c)if(this.Q[c]>0){this.N=g;break}if(!this.N)for(c=0;c<this.V.length;++c)if(this.V[c]>0){this.N=g;break}};
G.prototype._gts=function(){this.s.ma();var a=this.s.h,b=this.s.max,c=this.s.B.length;return[[c,a.k,a.n,a.i],[c,b.k,b.n,b.i]]};var V=function(a,b,c){b={la:b,va:c||0};a.push(b);a.sort(function(d,e){return e.va-d.va})};G.prototype._rce=function(a,b){V(this.r,a,b)};G.prototype._rd=function(a,b,c){b=b||"";this.L[b]||(this.L[b]=[]);V(this.L[b],a,c)};G.prototype._t=function(){return this.ja};G.prototype._rt=function(){return this.a.T()};G.prototype._p=function(){return w[this.a.M()]};G.prototype._i=function(a){return!!this.qa(a)};
G.prototype.qa=function(a){var b=this.ca(a);a=this.K(a,b);var c=C[b],d=E[b],e=i;if(a&&b)e=c&&c[a]?c[a]:d&&d.Ja(a,this.K);if(e){T(e);if(e.j.length)return e}return i};G.prototype._c=function(){if(this.A)O(1,3,this.r,this.a);else{this.A=g;this.a.close();this.a.Z(this);this.a=i}};G.prototype._ns=function(){this.ya++};var W=function(a){this.ra=a;this.i=this.n=this.k=i};W.prototype.xa=function(){this.i=this.n=this.k=0};var N=function(){this.ba={};this.B=[];this.U=0;this.h=new W("");this.max=new W("")};
l=N.prototype;l.Fa=function(a){var b=this.B[this.U];b&&delete this.ba[b];this.ba[a.ra]=a;this.B[this.U]=a.ra;this.U=(this.U+1)%10};l.ka=function(a,b,c,d){var e=this.ba[a];if(!e){e=new W(a);this.Fa(e)}if(b!=i&&e.k==i)e.k=b;if(c!=i)e.n=c;if(d!=i)e.i=(e.i||0)+d};l.Ta=function(a,b){this.ka(a,b,i,i)};l.Ua=function(a,b){this.ka(a,i,b,i)};l.Sa=function(a,b){this.ka(a,i,i,b)};
l.ma=function(){this.h.xa();this.max.xa();var a=this.B.length;if(a){for(var b=0;b<a;b++){var c=this.ba[this.B[b]],d=c.k||0,e=c.n||0;c=c.i||0;this.h.k+=d;this.h.n+=e;this.h.i+=c;this.max.k=Math.max(d,this.max.k);this.max.n=Math.max(e,this.max.n);this.max.i=Math.max(c,this.max.i)}if(a>1){this.h.k=(this.h.k-this.max.k)/(a-1);this.h.n=(this.h.n-this.max.n)/(a-1);this.h.i=(this.h.i-this.max.i)/(a-1)}}};
l.Ha=function(a,b){this.ma();var c=j,d=[this.h.k,this.h.n,this.h.i];if(this.B.length==10)for(var e=0;e<d.length;++e)if(a[e]>0&&d[e]>a[e]){c=g;break}var f=[this.max.k,this.max.n,this.max.i];if(!c)for(e=0;e<f.length;++e)if(b[e]>0&&f[e]>b[e]){c=g;break}return c?d.concat(f):i};var H=function(a,b,c,d,e){for(var f=c.g,h=0;f&&h<f.length;++h)O(a,b,f[h].r,c,d,e)},X=function(a,b,c,d){for(var e=0;e<b.length;++e)b[e]._d(a,c,d)},Y=function(a,b){for(var c=0;c<b.length;c++)if(b[c]==a){b.splice(c,1);break}};
window.google.td=function(a,b,c,d){var e={};if(b==3)e=z;else if(b==4)e=A;for(var f in e){b=e[f];b.na(a,c,d)}};var P=function(a,b){this.g=[];this.b=!!b;this.W=[];this.fa=1;this.v=a;this.G=1};l=P.prototype;l.J=function(a){this.g.push(a)};l.Z=function(a){Y(a,this.g)};
l.open=function(){try{var a=window.WebSocket;this.w=new a(this.v);this.G=2}catch(b){H(0,6,this,b);return j}var c=this;this.w.Va=function(){c.G=3;for(var d=0;d<c.W.length;++d)c.w.send(c.W[d]);c.W=[]};this.w.onmessage=function(d){var e=d.data;c.b||(e=I(d.data,c));e&&X(e,c.g)};this.w.onclose=function(){c.G!=4&&H(0,16,c);c.G=1};return g};l.close=function(){this.fa--;if(this.fa==0){this.G=4;this.w.close();delete y[this.v]}};
l.$=function(a){switch(this.G){case 3:this.w.send(a);break;case 1:case 4:H(1,11,this);break;case 2:this.W.push(a);break;default:H(1,17,this)}};l.T=function(){return this.w};l.M=function(){return 0};var R=function(a,b,c){this.m=a||"tlif"+google.time()+m++;this.b=!!b;this.ia=g;this.g=[];this.o=c||1;this.z=0;this.H=[];this.ha=[]},Z=o&&o<=7?1:0;l=R.prototype;l.J=function(a){this.g.push(a)};l.Z=function(a){Y(a,this.g)};
l.na=function(a,b){if(a&&(this.o==1&&a==this.m||this.o>1&&a.match("^"+this.m+"[0-9]+$")))X(b,this.g)};
l.open=function(){var a=document;if(google.browser.engine.IE)try{var b=window.google.ihtmlfile=new ActiveXObject("htmlfile");b.open();b.close();b.parentWindow.google=window.google;a=b}catch(c){H(1,2,this,c);return j}for(b=0;b<this.o;++b){var d=this.m+(this.o>1?b:"");if(!this.H[b])try{var e=a.createElement("IFRAME");e.name=d;e.style.display="none";e.src="about:blank";a.body.appendChild(e);this.H[b]=e.contentWindow}catch(f){H(1,5,this,f);return j}var h=this.H[b];if(!h)return j;(function(k,p,s,v){var n=
function(){k.Na(p,v)};s=document.getElementsByName(s);for(var q=0,r;r=s[q];++q)if(r.tagName=="IFRAME"){google.listen(r,"load",n);k.Ma(r)}k.Ga(p,v)})(this,h,d,b)}z[this.m]=this;return g};l.Na=function(a,b){try{var c=a.location.href,d=o<=7||a.document.readyState=="complete"}catch(e){H(1,13,this,e);return}try{if(!(/\/blank\.html$/.test(c)||/about:blank$/.test(c))&&!(a.Ka&&a.Ka.loc)&&d&&c.indexOf(this.ha[b])<0)H(1,19,this)}catch(f){H(1,7,this,f)}this.Oa(a)};l.Oa=function(a){if(Z==0&&a)a.src="about:blank"};
l.Ma=function(a){if(Z==0&&o>=8){var b=document.createElement("div");b.style.display="none";google.dom.insert(b,a)}};l.Ga=function(a,b){if(Z==1&&!this.ha[b])try{a.document.title=document.title}catch(c){}};l.close=function(){if(this.o==1){delete z[this.m];var a=window.frames[this.m];a.parent.removeChild(a)}else for(var b=0;b<this.o;b++){a=this.m+b;delete z[a];a=window.frames[a];a.parent.removeChild(a)}};
l.$=function(a,b){this.z=(this.z+1)%this.o;var c=this.m+(this.o==1?"":this.z);a+="&wrapid="+encodeURIComponent(c);c=this.H[this.z];if(Z==1)c.location.href=a;else c.location.replace(a);this.ha[this.z]=a;this.ia=!b};l.T=function(){return this.o==1?this.H[this.z]:this.H};l.M=function(){return 3};var S=function(a,b,c){this.m="tljp"+google.time()+m++;this.Ia=0;this.b=!!a;this.ia=g;this.g=[];this.F={};this.D=[];this.I=!!b;this.O=c||5};l=S.prototype;l.J=function(a){this.g.push(a)};l.Z=function(a){Y(a,this.g)};
l.open=function(){A[this.m]=this;return g};l.close=function(){A&&A[this.m]&&delete A[this.m];for(var a in this.F)this.S(a)};l.S=function(a){var b=this.F[a];if(b){delete this.F[a];for(var c=0;c<this.D.length;++c)if(this.D[c]==a){this.D.splice(c,1);break}window.setTimeout(function(){try{google.dom.remove(b);b.src="about:blank"}catch(d){}},0)}};l.na=function(a,b){this.F[a]&&X(b,this.g)};
l.$=function(a,b){var c=document.createElement("script"),d=this.m+this.Ia++;c.src=a+"&wrapid="+d;c.id=d;this.F[d]=c;this.D.push(d);var e=this;if(google.browser.product.IE)c.onreadystatechange=function(){var f=c.readyState;if(f=="loaded"||f=="complete")e.S(d)};else c.onload=function(){e.S(d)};document.body.appendChild(c);this.ia=!b;this.I&&this.D.length>this.O&&this.S(this.D[0])};l.T=function(){return this.F};l.M=function(){return 4};
var Q=function(a,b,c,d){this.ea=!!a;this.b=!!b;this.Ca=!!c;this.sa=d||5;this.X=[];this.p=[];this.ua=0;this.g=[]};l=Q.prototype;l.J=function(a){this.g.push(a)};l.Z=function(a){Y(a,this.g)};l.open=function(){var a=google.xhr();return!!a};l.close=function(){this.X=[];for(var a=0;a<this.p.length;++a){var b=this.p[a];if(b)b.onreadystatechange=function(){};b&&b.readyState!=0&&b.readyState!=4&&b.abort()}this.p=[]};
l.$=function(a,b){var c=google.xhr();c.open("GET",a);if(c){var d=this,e=function(h,k,p){X(h,d.g,k,p)},f=0;c.onreadystatechange=function(){try{if(c.readyState==4&&c.status==0){H(1,21,d,i,a);d.Y(c);d.aa();return}}catch(h){H(1,21,d,i,a);d.Y(c);d.aa();return}if((c.readyState==3||c.readyState==4)&&c.status==200&&!d.b&&(c.getResponseHeader("Content-Type")||"").indexOf("application/json")==-1){H(1,12,d,i,a);d.Y(c);d.aa()}else if(c.readyState==3&&d.ea)if(d.b)e(c.responseText,g,g);else f=$(c.responseText,
f,e,d,a);else if(c.readyState==4){if(c.status==200&&(!d.b||!d.ea||f==0))d.b?e(c.responseText,b,j):$(c.responseText,f,function(k){e(k,b)},d,a,g);else if(c.status>=400&&c.status<500)H(1,0,d,i,a);else c.status>=500&&c.status<600&&H(1,1,d,i,a);d.Y(c);d.aa()}};this.Da(c)}};l.Da=function(a){if(this.p.length<this.sa){a.send(i);this.p.push(a)}else if(this.Ca){var b=this.p.shift();b.onreadystatechange=function(){};b.abort();H(2,20,this);a.send(i)}else this.X.push(a)};
l.aa=function(){for(;this.ua<this.sa&&this.X.length>0;){var a=this.X.shift();if(a){a.send(i);this.ua++;this.p.push(a)}}};l.Y=function(a){for(var b=0;b<this.p.length;++b){var c=this.p[b];if(a==c){this.p.splice(b,1);break}}};var $=function(a,b,c,d,e,f){var h=a.split('/*""*/'),k=-1;f&&k++;for(f=b;f<h.length+k;++f){b++;if(h[f]){a=I(h[f],d,e);c(a)}}return b};Q.prototype.T=function(){return window.google.xhr()};Q.prototype.M=function(){return this.ea?1:2};})();
(function(){var f=true,h=null,j=false;var k=window.google.ac={},aa=j,ba,m=j,n=j,ca,da,ea,fa,ga,o,ha,p,q,ia,la,ma,na=j,s,t,u,v,w,x="",oa=h,y=h,z=h,A=-1,C,D,E,F,G,H,I,J,pa,qa,ra,K,L,sa,ta={},ua,M={},va,N=0,wa=j,xa=j,O=h,ya=0,za,Ba;var Da;
var Q,R,Fa=0,Ga=j,Ha=j,V={addPbx:j,addPsj:j,allowHideSuggestions:f,colorQuerySuggestionWithLinks:j,executeQueryOnEsc:j,fullWidth:j,maxShownSuggestions:-1,pp_msg1:"",pp_msg2:"",pp_msg3:"",pp_url:"",showFeelingLuckyLinks:j,showSearchButtons:f,smallLearnMoreDisclaimer:j,useKeyDown:j};function Ia(a){for(var b in a)V[b]=a[b]}function Ja(a){return(a=a&&a.match(/\D+$/))?a[0]:h}var Ka="hp",La="serp",Ma="img",Na={0:Ka,1:La,2:Ma},W;
function Oa(a){return(document.getElementById("gac_scont")||document.getElementById("main")||document.getElementById("xjsc")||document.body).appendChild(a)}function Pa(){google.msg.send(8)&&Qa()}
function Qa(){Ra();X();if(C){J.value=pa.value=qa.value=K.value=ra.value="";window.clearTimeout(oa);x=Ba=ua="";oa=y=z=h;A=-1;N=ya=0;wa=j;W=0;ta={};Da=0;Fa=0}}
var Sa={ds:1,hl:1,client:1,expIds:1,tok:1,xhr:1,q:1,cp:1},Ta=function(a){a=a.substring(a.indexOf("?")+1);a=a.split("&");for(var b=[],c={},d=0,e;e=a[d++];){var g=e.split("=");if(g.length==2){g=g[0];if(Sa[g]&&!c[g]){b.push(g=="q"?e.toLowerCase().replace(/\+/g," "):e);c[g]=f}}}b.sort();return decodeURIComponent(b.join("&"))};function Ua(a,b,c){google.msg.send(17,[a,b,c],j)&&Va()}
function Wa(a,b,c,d,e,g){if(e)return f;if(c)a=c();try{if(typeof a=="string")a=eval("("+a+")");b(a,g)}catch(i){a={_response:a,_url:d,_isPartial:e,_opt_fromCache:g};google.ml(i,j,a)}return f}function Xa(){var a={};a[5]=4;a=[a];if((R=window.google.gtr(a))&&R._o()){R._rd(function(b,c,d,e,g,i){Wa(b,Ya,c,d,e,g,i)},"/complete/deleteitems");R._rd(function(b,c,d,e,g,i){Wa(b,Za,c,d,e,g,i)},"/complete/init")}}function Va(){var a=[{},{},{}];a[0][5]=4;a[1][5]=2;a[2][5]=1;a=window.google.gtr(a);a._o();$a(a)}
function $a(a){if(a){Q&&Q._c();Q=a;Q._rce(Ua,10);Q._ckf(Ta,"/complete/search");a="/s";Q._ckf(Ta,a);Q._rd(function(b,c,d,e,g,i){Wa(b,ab,c,d,e,g,i)},"/complete/search");Q._t()!=4?Q._rd(function(b,c,d,e,g,i){Wa(b,ab,c,d,e,g,i)},a):Q._rd(function(){},a)}}function bb(a,b){W=0;if(a=="i")W=2;else if(b&&b!="")W=1}function cb(){if(C){if(V.addPbx&&!Ga){Y("pbx","1");Ga=f}if(V.addPsj&&!Ha){Y("psj","1");Ha=f}if(!V.addPsj&&Ha){var a=C.psj;if(a){C.removeChild(a);Ha=j}}}}
function db(a,b,c,d,e,g){Q||Va();if(!b){a=document.f||document.gs;b=a.q}if(!(!google.msg.send(13,[b,c])&&D)){bb(c,d);eb();g&&fb(g);gb();C=a;D=b;v=w=u=D.value;if(!b.init){za=document.getElementsByTagName("head")[0];google.listen(C,"submit",hb);google.listen(D,"paste",function(i){return ib(i)});google.listen(D,"cut",function(i){return ib(i)});D.setAttribute("autocomplete","off");V.allowHideSuggestions&&google.listen(D,"blur",X);D.onkeypress=jb;google.listen(D,"keyup",kb);J=Y("aq","f");pa=Y("aqi","");qa=Y("aql","");K=Y("oq",v);ra=Y("gs_rfai","");Ga=Ha=j;cb();H=G=document.createElement("table");G.cellSpacing=G.cellPadding="0";I=G.style;G.className="gac_m";if(t){H=E=document.createElement("div");E.className="gac_od";I=E.style;Oa(E);F=document.createElement("div");F.cellSpacing=E.cellPadding="0";F.className="gac_id";E.appendChild(F);
F.appendChild(G)}else C.appendChild(G);sa=document.createElement("div")}b.init=f;X();lb();if(!aa){mb();aa=f}a=Na[W];a="&client="+a;c=c?"&ds="+c:"";d=["?hl=",google.kHL,a,nb(),c,"&sugexp=ldymls",(d?"&pq="+encodeURIComponent(d):"")].join("");ua="/complete/search"+d;Ba="/complete/deleteitems"+d;Da=ob();google.listen(window,"pageshow",function(i){if(i.persisted){J.value="f";K.value=D.value}});pb();d=ia||e&&e.length||"https:"==document.location.protocol;
la=["http",d?"s":"","://"].join("");if(d&&o){Xa();va=e;qb()}}}function ib(a){if(!rb(a,-1))return j;window.setTimeout(function(){v=D.value;m=j;if(v)n=j;Da=ob();},0);return f}function rb(a,b){if(!google.msg.send(14,[b,a])){a.cancelBubble=f;return a.returnValue=j}return f}
function mb(){function a(d,e){b.push(d,"{",e,"}")}var b=[];if(t){var c="background:white;margin:0;z-index:100;";a(".gac_od",c+"border-top:0;border-left:0;border-right:1px solid #e7e7e7;border-bottom:1px solid #e7e7e7;margin-top:1px;padding:0!important;position:absolute");a(".gac_id",c+"border-top:1px solid #a2bff0;border-left:1px solid #a2bff0;border-right:1px solid #558be3;border-bottom:1px solid #558be3;display:block;position:relative");a(".gac_m",c+"border:0;cursor:default;display:block;font-size:17px;line-height:117%;padding:0;position:relative")}else a(".gac_m",
"background:white;border:1px solid #666;cursor:default;font-size:17px;line-height:117%;margin:0;position:absolute;z-index:99");a("#gac_pp","color:#a1b9ed;text-decoration:none;cursor:pointer;font:22px Arial,sans-serif;height:20px;line-height:22px;margin:0 2px 0 0;padding:4px 0 0 0;top:4px;width:8px");a("#gac_pp:hover","color:#4272db;text-decoration:none");a("#gac_lm","color:#4272db;text-decoration:none");a("#gac_lm:hover","color:#4272db;text-decoration:underline");a(".gac_m td","line-height:22px");
a(".gac_n","padding-top:1px;padding-bottom:1px");a(".gac_b td.gac_c","background:#d5e2ff");a(".gac_b","background:#d5e2ff");a(".gac_k","display:none");a(".gac_b td.gac_k","display:block");a(".gac_a td.gac_f","background:#fff8dd");a(".gac_p","padding:1px 4px 2px 3px");a(".gac_u","padding:0 0 1px 0;line-height:117%;text-align:left");a(".gac_t","width:100%;text-align:left;font-size:17px");
a(".gac_za","position:absolute;bottom:0;right:0;text-align:right;font-size:12px;padding-right:5px");a(".gac_bt","width:"+(D.offsetWidth-2)+"px;text-align:center;padding:8px 0 7px;position:relative");a(".gac_sb","font-size:15px;height:28px;margin:0.2em");a(".gac_z","white-space:nowrap;color:#c00");a(".gac_s","height:3px;font-size:1px");c=t?7:3;c="white-space:nowrap;overflow:hidden;text-align:left;padding-left:"+
c+"px;padding-right:3px";a(".gac_c",c);a(".gac_e","text-align:right;padding:0 3px 0 8px;white-space:nowrap");a(".gac_d","font-size:13px");a(".gac_h","color:green");a(".gac_j","display:block");a(".gac_l","line-height:18px");a(".gac_x","display:block;line-height:16px");a(".gac_i","color:#666");a(".gac_w img","width:40px;height:40px");a(".gac_w","width:1px");a(".gac_r",
"color:red");a(".gac_v","padding-bottom:5px");c=document.createElement("style");c.setAttribute("type","text/css");za.appendChild(c);b=b.join("");c.appendChild(document.createTextNode(b));}
function lb(){if(H&&D.parentNode){var a=sb(D);I.left=a.F+"px";I.top=a.H+D.offsetHeight-1+"px";a=D.offsetWidth;if(V.fullWidth){var b=document.getElementById("sftab");if(b)a=b.offsetWidth}a-=3;if(a>=0){if(t)I.minWidth=a+"px";else I.width=a+"px";if(y)if(b=Z(0))b.firstChild.style.width=a+"px"}}}
function sb(a){for(var b=0,c=0;a;){b+=a.offsetTop;c+=a.offsetLeft;a=a.offsetParent}return{H:b,F:c}}function Y(a,b){var c=document.createElement("input");c.type="hidden";c.name=a;c.value=b;return C.appendChild(c)}
function jb(a){var b=a.keyCode;wa=n=j;if(!rb(a,b))return j;if(b==27&&tb())return ub(a,f);if(b==13)return ub(a);if(vb(b,a)){wa=f;return j}V.useKeyDown&&window.setTimeout(function(){wb(b,a)},0)}function xb(){return!!z&&!!xa}function ub(a,b){if(!b||V.executeQueryOnEsc)zb(j);b&&X();a.cancelBubble=f;return a.returnValue=j}
function zb(a){if(!a&&L){C.removeChild(L);L=h}if(z&&A!=-1&&xa&&!(a&&z.D))z.onclick(h);else if(D.value=="")X();else{if(a){L=Y("btnI","1");if(z)D.value=z.b}Ab()}}function Ab(){hb();C.onsubmit&&C.onsubmit()==j||C.submit()}function kb(a){var b=a.keyCode,c=vb(b,a);if(c)wa&&wb(b,a);else V.useKeyDown||wb(b,a);wa=j;}
function wb(a,b){if(D.value!=u){if(V.useKeyDown)w=v;v=D.value;m=j;Da=ob();K.value=v}if(vb(a,b)){Bb(a==40);xa=tb()}lb();if(x!=v&&!O&&V.allowHideSuggestions)O=window.setTimeout(X,500);u=D.value}function vb(a,b){if(a==38||a==40)return!b||!(b.ctrlKey||b.altKey||b.shiftKey||b.metaKey);return j}function Cb(){if(z){z.className="gac_a";z=h;A=-1}}
function Db(){xa=j;if(!ya){if(z)z.className="gac_a";z=this;for(var a=0,b;b=Z(a);a++)b==z&&(A=a);z.className="gac_b"}}function Eb(a,b){return function(c){Fb(Gb(a),b);$(c);return j}}function Gb(a){return[a,"&aq=",z.v,"&oq=",K.value,Hb("aqi",pa),Hb("aql",qa),Hb("gs_rfai",ra)].join("")}
function Hb(a,b){if(b&&b.value.length&&a.length)return["&",a,"=",b.value].join("");return""}function Fb(a,b){var c=window.frames.wgjf;if(c&&!b){google.r=1;c.location.replace(a)}else window.location=a}
function Ib(){if(google.msg.send(23,[this.b,v])){Jb(this.b);Ab();}}
function Bb(a){if(!(v!=x||!y||!y.length))if(tb()){if(z)z.className="gac_a";for(var b=z,c=A,d=y.length,e=(A+1+(a?1:d))%(d+1)-1;e!=-1&&Z(e).w;)e=(e+1+(a?1:d))%(d+1)-1;A=e;if(A==-1){Kb();google.msg.send(12,[c,b,b&&b.b||"",A,h,v])}else{z=Z(e);z.className="gac_b";Jb(z.b);m=f;J.value=z.v;google.msg.send(12,[c,b,b&&b.b||"",A,z,z.b])}}else Lb()}function Kb(){D.focus();Jb(v);z=h;J.value="f"}
function X(){if(google.msg.send(11)){if(O){window.clearTimeout(O);O=h}I&&(I.visibility="hidden");}}function Lb(){if(google.msg.send(22)){I&&(I.visibility="visible");lb();ya=1}}function tb(){return!!I&&I.visibility=="visible"}
function Ra(){if(G){G.innerHTML="";}}function Mb(a,b,c){a.onclick=b?Eb(b,c):Ib;a.D=!b;a.onmousedown=Nb;a.onmouseout=Cb;a.onmouseover=Db;a.onmousemove=function(){if(ya){ya=0;Db.call(this)}}}
function Ob(a,b){$(a);for(var c=0,d;d=Z(c++);)if(d.v==b){if(R){c=[la,"clients1.google.gr",Pb(Ba,"delq",d.b)].join("");R._s(c)}break}return j}function qb(){if(R){var a=[la,"clients1.google.gr","/complete/init"];va&&a.push("?tok=",encodeURIComponent(va));a=a.join("");R._s(a,j)}}function Za(a){M=a;M.ts=google.time()}
function Ya(a){for(var b=0,c;c=Z(b++);)if(Ja(c.v)=="p"&&c.b==a[0]){c.w=1;c.onclick=c.onmouseover=h;if(c==z){c.className="gac_a";A=-1;Kb()}c.A.className="gac_c gac_i fl";c.A.innerHTML="This search was removed from your \x3ca href\x3d\x22/history\x22\x3eWeb History\x3c/a\x3e"}}function Qb(a){return a.toLowerCase().replace(/\s+/g," ").replace(/^ /,"")}function Rb(a,b,c){a=Qb(a);b=Qb(b);c=Qb(c);if(a.indexOf(b)==0){if(a.indexOf(c)==0)return b.length>=c.length;return f}return j}
function ab(a,b){function c(gc,yb){var ja=yb?Ja(yb[2]):h;ja=gc+(ja?"-"+ja:"");if(ja!=ka){if(Aa)S+=ka+Aa;Aa=0;ka=ja}Aa++}var d=a[0];N>0&&N--;if(!(n||!G)){var e=a[1],g=v.toLowerCase(),i=e[0],l=a[0],r=f;if(d.toLowerCase()!=g&&(!i||!g||!Sb(g,i))||!Rb(v,l,x))r=j;if(google.msg.send(9,[l,r?e:h,G,b,!!a[6],r])&&r){if(O){window.clearTimeout(O);O=h}x=l;Cb();Ra();var S="",ka,Aa=0;d=e.length-1;g=V.maxShownSuggestions;if(g!=-1)d=Math.min(d,
g-1);g=0;for(var T,U,B;g<=d;++g)if(B=e[g])if(l=ta[B[1]]){l.B&&l.B(g,d)&&Tb();T=B[2];i=B[3];U=l.k?l.k(B,i):h;r=G.insertRow(-1);Mb(r,U,l.C);r.v=T;r.className="gac_a";U=r.A=document.createElement("td");U.className="gac_c";l.g(U,T,B,i);T=l.m;r.b=T?T(B,i,x):B[0];r.appendChild(U);c(l.e,B);g<d&&l.G&&Tb()}qa.value=a[3]||"";ra.value=a[4]||"";if((y=G.rows)&&y.length>0){if(W==0){Vb();if((e=!V.showSearchButtons)&&(q||p))Wb()}else if(W==1&&(q||p))Wb();na||Xb();ma&&Yb();Lb()}else X();c("");pa.value=S;A=-1}}}function Wb(){var a=V.smallLearnMoreDisclaimer,b=Tb(),c=b.style;c.textAlign="right";c.fontSize=a?"11px":"12px";c.paddingRight="5px";if(a)c.lineHeight="14px";b.innerHTML=Zb()}
function Sb(a,b){var c=b[0];if(!c||a.length>2*c.length)return j;a=a.replace(/[^\s0-9a-z+_\-.]/g,"");return(a=Qb(a))?$b(c).indexOf(a)==0:j}function Z(a){b=y.item(a);return b}
function ac(a){var b=a?"I\x26#39;m Feeling Lucky":"Google Search",c="gac_sb",d="",e="";if(t){c="lsb";}return[''].join("")}
function Vb(){if(V.showSearchButtons){var a=bc(),b="";if(q||p)b="<div class=gac_za>"+Zb()+"</div>";a=a.insertCell(0);a.innerHTML=['<div style="position:relative"><div class=gac_bt>',ac(j),ac(f),"</div>",b,"</div>"].join("")}}function cc(a){var b;try{if(window.localStorage)b=window.localStorage.getItem(a)}catch(c){}if(b){if(typeof b.value=="string")b=b.value;return parseInt(b,10)}return 0}
function dc(a){try{var b=window.localStorage;if(b&&!b.readonly){(a=a)||(a=cc("web-ac-p2")+1);b["web-ac-p2"]=""+a}}catch(c){}}function Xb(){(ma=google.kHL=="en"&&ha&&V.pp_url&&cc("web-ac-p")<999&&cc("web-ac-p2")<3)&&dc();na=f}
function Yb(){var a=bc();a.id="p_pl";a=a.insertCell(0);var b=a.style;b.borderTop="1px solid #598ee3";b.background="#dcebfa";b.backgroundImage="url(/images/pp_gbg.png)";b.backgroundRepeat="repeat-x";if(!s){var c;c=V.pp_url;c=["<span style=white-space:nowrap>",V.pp_msg2,'.</span> &nbsp;<span style=white-space:nowrap><a href="',
c,'" class=fl>',V.pp_msg3,"</a></span>"].join("");s=document.createElement("div");s.className="gac_c";s.style.paddingTop="1px";s.innerHTML=['<table cellpadding=0 cellspacing=0 border=0 style=width:100%><tr><td style="width:100%;text-align:center;padding-top:4px">',V.pp_msg1,'<br><div style="font-size:12px;white-space:normal">',c,'</div><td style=vertical-align:top><a id=gac_pp title="Dismiss" href="#" onclick="return google.ac.x(event)">&times;</a></table>'].join("")}a.appendChild(s)}
function ec(a){document.getElementById("p_pl").style.display="none";dc(999);$(a);return ma=j}function bc(){var a=G.insertRow(-1);a.w=1;a.onmousedown=Nb;return a}function Zb(){var a="fr",b="En savoir plus";if(q){a=google.kHL;b="Learn more"}return["<a ",V.smallLearnMoreDisclaimer?"id=gac_lm ":"",'href="http://www.google.com/support/websearch/bin/answer.py?hl=',a,'&answer=106230">',b,"</a>"].join("")}
function $b(a){return a.replace(/<\/?[b|em]>/gi,"")}function fc(a,b){return['href="',a,'" onmousedown="google.ac.r(event, this, \'',b,'\')" onclick="return google.ac.c(event)"'].join("")}function hc(a,b,c){ba=j;if(a.which)ba=a.which==2;else if(a.button)ba=a.button==4;b.href=Gb(c)}function ic(a){if(ba){$(a);return f}return j}
function $(a){if(a){a.stopPropagation();a.cancelBubble=a.cancel=a.returnValue=f}}
function Tb(){var a=G.insertRow(-1);a.w=1;a.onmousedown=Nb;a=a.insertCell(0);a.className="gac_s";return a}function hb(){var a=v;if(y){var b=Z(A);if(b)a=b.b}n=f;b=!!L;if(google.msg.send(15,[a,b])){X();if(y&&Z(A)&&K.value!=D.value)J.value=Z(A).v;else{K.value="";J.value="f";if(N>=10||Fa>=3)J.value="o"}kc(f)}}function lc(){if(!(Fa>=3)){if(!m&&v!=D.value){w=v;v=D.value}if(w!=v)if(google.msg.send(10,[v])&&v){mc(ua,"q",v)&&N++;D.focus()}w=v}}
function kc(a){u=v=D.value;n=m=j;if(a)w=v;return Pb(ua,"q",v)}function nc(){return ua}function oc(){return x}function pb(){lc();for(var a=100,b=1;b<=(N-2)/2;++b)a*=2;a+=50;oa=window.setTimeout(pb,a)}
function Pb(a,b,c){a=[a,"&xhr=t","&",b,"=",encodeURIComponent(c),"&cp="+Da];var d=google.enc;if(!d||!d.b64d)d=google;if(o&&M&&M.websafe_signing_key&&d&&d.b64d){var e=d.b64d(M.websafe_signing_key);b=d.b64e(c);e=new d.HMAC(new d.MD5,e);e.update(c);c=d.b64e(e.digest());a.push("&qe="+b);a.push("&qesig="+c);a.push("&pkc="+M.pkc)}return a.join("")}
function mc(a,b,c){a=Pb(a,b,c);a=google.msg.send(16,[a],a);if(!a)return j;if(Q._t()==4)a=la+"clients1.google.gr"+a;Q._s(a);o&&M&&M.ts!==undefined&&google.time()-M.ts>828E5&&qb();return f}function Jb(a){if(D){D.value=u=a;m=j}}function Ub(a,b){a.appendChild(document.createTextNode(b))}
function Nb(a){a.stopPropagation();return j}
function ob(){if(document.selection){var a=document.selection.createRange();return Math.abs(a.moveStart("character",-D.value.length))}try{a=D.selectionStart;return typeof a=="undefined"?0:a}catch(b){return 0}}function eb(){ca=f;ea=ia=q=p=da=j;fa=f;ga=j;o=f;t=ha=j}function fb(a){if("a"in a)ca=a.a;if("c"in a)da=a.c;if("f"in a)p=a.f;if("l"in a)ea=a.l;if("lm"in a)q=a.lm;if("n"in a)fa=a.n;if("o"in a)ga=a.o;if("r"in a)ha=a.r;if(W==2)o=j;else if("p"in a)o=a.p;if("s"in a)ia=a.s;if("sw"in a)t=a.sw}
function gb(){var a=[pc];ca&&a.push(qc);da&&a.push(rc);ea&&a.push(sc);fa&&a.push(tc);ga&&a.push(uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc);Ec(a)}function Ec(a){for(var b=0,c;c=a[b++];)ta[c.j]=c}
function Fc(a,b,c){var d=V.showFeelingLuckyLinks,e="width:100%";if(c&&V.colorQuerySuggestionWithLinks)e+=";color:#52188c";b=["<table cellpadding=0 cellspacing=0 border=0 class=gac_t>","<tr>",'<td class=gac_c style="',e,'">',b];c&&d&&b.push('<span class="gac_d gac_e">',c,"</span>");d&&!/[?&#]tbs=\S/.test(window.location.href)&&b.push('<td class="gac_d gac_e gac_k">','<a href=#ifl class=fl onclick="google.ac.rd(true);return false">',"I\x26#39;m Feeling Lucky &raquo;","</a>");c&&!d&&b.push('<td class="gac_d gac_e">',
c);b.push("</table>");a.className="";a.innerHTML=b.join("");}
var qc={j:8,e:"a",G:f,m:function(a,b,c){return c},k:function(a,b){return b[1]+nb()},B:function(a,b){return a==b},g:function(a,b,c,d){b=d[0];var e=d[1]+nb();c=d[2];var g=d[3];d=d[4];a.className="gac_f gac_p";var i=$b(b);e=fc("http://"+i,e);a.innerHTML=['<table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td><table cellpadding=0 cellspacing=0 border=0 class=gac_t><tr><td style="line-height:117%;vertical-align:bottom"><a class=q ',e,">",c,'</a><td class="gac_e gac_d gac_i">Sponsored Link</table><tr><td class="gac_d gac_u gac_x" style="line-height:16px;padding-bottom:8px"><span class=gac_h',">",b,"</span>&nbsp; &nbsp;",g,d?" "+d:"","</table>"].join("")}},zc={j:11,e:"b",C:f,k:function(a,b){return b[0]},g:function(a,b,c,d){b=d[0];c=d[1];var e=d[2],g=d[3],i=d[4],l=d[5],r=d[6];d=d[7];var S=b.match(/^([^&]*)/)[1];a.innerHTML=['<span class="gac_j gac_l"><a class=q ',fc(S,b),"><b>",c,"</b> - ",e," (",g,")</a><br><b>",i,"</b> <span class=gac_d><span class=gac_",l>=0?"h":"r",">",l," (",r,"%)</span> ",d,' - </span><a href=/help/stock_disclaimer.html class="gac_d fl" onclick="google.ac.p(event);return true">Disclaimer</a></span>'].join("")}},
Ac={j:12,e:"c",k:function(a,b){return b[0]},g:function(a,b,c,d){b=d[0];c=d[1];d=d[2];for(var e="",g=d.length-1,i=0,l;i<g;i++){l=d[i];e+=[l[0],'<div class="gac_v">',l[1],"</div>"].join("")}l=d[g];e+=[l[0],"<br>",l[1]].join("");Gc(1,a,c,b,"www.flightstats.com",e)}},Bc={j:15,e:"d",g:function(a,b,c,d){b=d[0];c=d[1];var e=d[2];d=d[3];a.innerHTML=["<b>",b,"</b> ",e," (",c,") in <b>",d,"</b>"].join("")}},Cc={j:13,e:"e",k:function(a,b){return b[0]},g:function(a,b,c,d){b=d[0];c=d[1];d=d[2];Gc(1,a,c,b,d)}},
vc={j:14,e:"f",k:function(a,b){return b[0]},g:function(a,b,c,d){b=d[0];c=d[1];var e=d[2];d=d[3];Gc(1,a,c,b,d,e)}},pc={j:0,e:"g",m:function(a){return a.b},g:function(a,b,c){var d=c[0];a.innerHTML=d;c.b=Hc(a);c="";if(o&&Ja(b)=="p")c=["<a href=#ps class=fl onclick=\"return google.ac.dc(event,'",b,"')\">Remove</a>"].join("");Fc(a,d,c)}},wc={j:19,e:"h",g:function(a,b,c,d){b=d[0];d=d[1];a.innerHTML=["<b>",b," = ",d,"</b>"].join("")}},uc={j:17,e:"i",k:function(a,b){return b[3]},
g:function(a,b,c,d){b=d[0];c=d[1];var e=d[2];d=d[3];var g=d.match(/url=([^&]*)/)[1];a.innerHTML=['<span class="gac_j gac_l"><a ',fc(g,d),">",b," &#151; ",c,": ",e,'</a><span class=gac_d style="line-height:16px"><br>According to <span class=gac_h>',g,"</span></span></span>"].join("")}},Dc={j:10,e:"j",g:function(a,b,c,d){b=d[0];c=d[1];var e=d[4];d=d[5];var g=function(i){var l=i[0],r=i[1],S=i[2],ka=i[3];i=i[4];return['<td class=gac_w><img src="',l,'" alt="',r,'" title="',r,'"><td class="gac_c" style="line-height:112%;vertical-align:top">',
i,"<br>",S,"&deg; | ",ka,"&deg;"].join("")};a.innerHTML=["<b>Weather:</b> ",e,"&deg;",c," in ",b,"<br><table class=gac_t><tr>",g(d[0]),g(d[1]),g(d[2]),g(d[3]),"</table>"].join("")}},xc={j:20,e:"k",g:function(a,b,c,d){b=d[0];d=d[1];a.innerHTML=["<b>",b," = ",d,'</b> - <a href=/intl/en/help/currency_disclaimer.html class="gac_d fl" onclick="google.ac.p(event);return true">Disclaimer</a>'].join("")}},yc={j:16,e:"l",m:function(a,b){return"define: "+b[0]},g:function(a,b,c,d){b=d[0];c=d[1];d=d[2];Gc(1,
a,"Web definitions for <b>"+b+"</b>","/search?q=define:"+b.replace(" ","+"),"www.google.gr",[c," - <span class=gac_i>",d,"</span>"].join(""))}},sc={j:30,e:"m",m:function(a){return a.b},g:function(a,b,c){b=c[0];sa.innerHTML=b;c.b=Hc(sa);a.innerHTML=["<span class=gac_z>Did you mean: </span>",b].join("")}};function Hc(a){var b;b=a.textContent;return b}
var tc={j:5,e:"n",m:function(a,b,c){return c},k:function(a,b){return b[0]},g:function(a,b,c,d){b=d[0];d=d[1];a.className="gac_c gac_n";a.style.lineHeight="117%";var e=c[0];c=e.replace(/HTTPS?:\/\//gi,"");e=$b(e);/^HTTPS?:\/\//i.test(e)||(e=(b.indexOf("/url?url=https:")>0?"https":"http")+"://"+e);b=fc(e,b);a.innerHTML=["<span class=gac_x><a ",b,">",d,'</a><br><span class="gac_d gac_h"',">",c,"</span></span>"].join("");}},rc={j:32,e:"o",m:function(a){return a.b},g:function(a,b,c,d){d=d[1];b=c[0];sa.innerHTML=b;c.b=Hc(sa);c=['<a href="',d,'" class=fl onclick="google.ac.p(event);return true">In Contacts</a>'].join("");Fc(a,b,c)}};
function Gc(a,b,c,d,e,g,i){var l=d.indexOf("/url")?d:d.match(/url=([^&]*)/)[1];b.style.lineHeight="112%";b.innerHTML=["<a class=q ",fc(l,d),">",c,'</a><span class="gac_d'+(a?" gac_x":"")+'">',g?g+"<br>":"",i?i+"<br>":"",e?"<span class=gac_h>"+e+"</span></span>":""].join("")}function nb(){if(google.kEXPI)return"&expIds="+google.kEXPI;return""}
k.c=ic;k.cp=ob;k.cq=oc;k.ct=Ra;k.d=Ya;k.dc=Ob;k.ds=Qa;k.h=ab;k.hs=X;k.i=db;k.p=$;k.ps=lb;k.r=hc;k.rd=zb;k.ru=nc;k.sa=xb;k.sr=lc;k.st=$a;k.sv=Ia;k.ui=kc;k.uhi=cb;k.x=ec;
k.u=Jb;google.listen(window,"resize",lb);google.dstr&&google.dstr.push&&google.dstr.push(Pa);})();
(function(){window.ManyBox={};var d,g,h=1,k=google.History.client(i),l=[],n;ManyBox.delayedRegister=function(a){l.push(a)};function o(a){for(var b in d)if(d[b].b&&a(d[b]))break}function p(a,b,c,e,f){this.b=a;this.k=b;this.F=e;this.q=f;this.s="/mbd?jsid="+a+(b?"&docid="+b:"")+"&resnum="+a.replace(/[^0-9]/,"")+"&mbtype="+e+"&usg="+c+"&hl="+(google.kHL||"");this.e={};this.o="";g[a]={u:0,H:this.e,k:this.k,j:0};this.p=0}p.prototype.append=function(a){this.o+="&"+a.join("&")};
function q(a,b){a.h.style.paddingTop=b+"px";a.h.style.display=a.h.innerHTML?"":"none";if(b>a.p)a.p=b;a.i.style.fontSize=b+"px";a.i.style.fontSize=null}
function s(a){if(!a.D){a.D=1;a.d=document.getElementById("mbb"+a.b);if(a.d){a.m=0;a.a=document.getElementById("mbl"+a.b);if(a.a){a.i=a.a.getElementsByTagName("DIV")[0];a.r=a.a.getElementsByTagName("A")[0];a.C=a.r.innerHTML;a.q=a.q||a.C;a.i.title=n&&n.m_tip;a.a.I=function(b,c){var e=google.style.getPageOffsetStart(a.a),f=google.style.getPageOffsetTop(a.a);return b>e-5&&b<e+google.style.getWidth(a.a)+5&&c>f-5&&c<f+google.style.getHeight(a.a)+5};a.h=document.getElementById("mbf"+a.b);q(a,0);a.a.onmousedown=
t(a);a.a.onclick=u(a);a.a.go=function(){a.a.onmousedown();a.a.onclick()}}else delete d[a.b]}else delete d[a.b]}}function v(a){google.log("manybox",[a.m?"close":"open","&id=",a.b,"&docid=",a.k,"&mbtype=",a.F,a.o].join(""))}
function t(a){return function(){if(g[a.b].j)a.L++<3&&v(a);else{if(a.e.n)v(a);else{var b=google.xhr();if(b){b.open("GET",a.s+a.o+"&zx="+google.time());a.w=0;b.onreadystatechange=function(){if(b.readyState==4){var c=0;if(b.status==200)try{eval(b.responseText);c=1}catch(e){}if(!c&&!a.G){g[a.b].j=0;a.G=1;a.s+="&cad=retry";a.a.onmousedown()}else{a.z&&w(a);a.w=0}}};a.w=1;b.send(null)}}g[a.b].j=a.L=1}}}function u(a){return function(){g[a.b].j||a.a.onmousedown();(a.z=a.w)||w(a)}}
function x(a){if(!a.e.n){a.e.n=n&&n.m_error;a.J=a.a.onclick;a.a.onclick=function(){h=0;w(a);h=1;a.c.parentNode.removeChild(a.c);g[a.b].j=a.e.n=a.A=0;a.a.onclick=a.J}}if(!a.A){a.A=1;var b=document.getElementById("res");a.K=b&&google.style.getPageOffsetStart(a.d)>google.style.getPageOffsetStart(b)+google.style.getWidth(b);a.c=document.createElement("div");q(a,0);a.c.style.position="absolute";a.c.style.paddingTop=a.c.style.paddingBottom="6px";a.c.style.display="none";a.c.className="med";b=document.createElement("div");
a.c.appendChild(b);b.className="std";b.innerHTML=a.e.n;a.h.parentNode.insertBefore(a.c,a.h)}}function i(a){h=0;ManyBox.init();o(function(b){if(b.k==a[b.b].k){b.e=a[b.b].H;a[b.b].u!=b.m&&w(b)}else a[b.b].j=0});g=a;h=1;google.History.save(k,g)}ManyBox.create=function(a,b,c,e,f){return new p(a,b,c,e,f)};ManyBox.register=function(a,b,c,e,f){return d[a]=ManyBox.create(a,b,c,e,f)};
google.listen(document,"click",function(a){a=a||window.event;for(var b=a.target||a.srcElement;b.parentNode;){if(b.tagName=="A"||b.onclick)return;b=b.parentNode}o(function(c){if(c.a.I(a.clientX,a.clientY)){c.a.go();return 1}})});function y(){d={};g={};l=[];history.navigationMode=history.navigationMode&&"fast"}y();ManyBox.init=function(a){if(a)n=a;for(a=0;a<l.length;a++)try{l[a].func()}catch(b){delete d[l[a].id]}l=[];o(s)};
function z(a,b){a.c.style.clip="rect(0px,"+(a.d.width||"34em")+","+(b||1)+"px,0px)"}p.prototype.insert=function(a){this.e.n=a};function A(a){a.g=document.getElementById("mbcb"+a.b);var b=a.g&&a.g.getAttribute("mbopen");if(b){eval(b);a.onopen(a.g)}}function B(a){a.c.style.display="none";a.i.style.backgroundPosition="-153px -70px";a.r.innerHTML=a.C;a.m=g[a.b].u=0;google.History.save(k,g)}
function C(a,b,c,e,f){var m=c>0?150:75,j=google.time()-f;m=j<m&&h?j/m*c:e>1?c-10:c;j=Math.max(a.v,b+m);var r=j-a.v;z(a,r);a.d.style.height=j<0?0:r?j+"px":"";q(a,Math.max(0,r-5));google.rhs();Math.abs(m)<Math.abs(c)?window.setTimeout(function(){C(a,b,c,e-1,f)},30):window.setTimeout(function(){c<0?B(a):A(a);if(!google.browser.engine.IE&&a.K)a.c.style.width="100px";a.c.style.position=a.d.style.height="";q(a,0);google.rhs();a.d.B=0},0)}
function w(a){a.z=0;if(!a.d.B){a.d.B=1;var b;if(a.m){if(b=a.g&&a.g.getAttribute("mbclose")){eval(b);a.onclose(a.g)}b=a.v-google.style.getHeight(a.d);a.h.style.display="none";q(a,a.p);a.c.style.position="absolute"}else{a.v=google.style.getHeight(a.d);x(a);q(a,0);a.p=0;o(function(c){c.i.title=""});a.i.style.backgroundPosition="-153px -84px";a.r.innerHTML=a.q;z(a,1);a.c.style.position="absolute";a.c.style.display="";a.m=g[a.b].u=1;google.History.save(k,g);b=a.c.offsetHeight}C(a,google.style.getHeight(a.d),
b,google.browser.product.SAFARI?2:1,google.time())}}google.register(22,{init:ManyBox.init,dispose:y});})();
(function(){var j,k;
function o(){j=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(j);k=j.sheet;}
google.addCSSRule=function(a,b){j||o();c=a+"{"+b+"}";k.insertRule(c,k.cssRules.length);};google.acrs=function(a){a=a.split(/{|}/);for(var b=1;b<a.length;b+=2)google.addCSSRule(a[b-1],a[b])};google.Toolbelt.ascrs=function(){};
var p,q;function r(){google.nav(document.getElementById("tbpi").href)}function t(a){google.srp.updateLinksWithParam("tbo",a?"1":"",google.srp.isSerpLink,google.srp.isSerpForm)}
function u(){mbtb1.insert=function(b){try{v(eval(b))}catch(c){r()}};var a=google.xhr();if(a){a.open("GET",[google.base_href.indexOf("/images?")==0?google.base_href.replace(/^\/images\?/,"/mbd?"):google.base_href.replace(/^\/search\?/,"/mbd?"),"&mbtype=29&resnum=1&tbo=1",mbtb1.tbs?"&tbs="+mbtb1.tbs:"","&docid=",mbtb1.docid,"&usg=",mbtb1.usg,"&zx=",google.time()].join(""),true);a.onreadystatechange=function(){if(a.readyState==4)if(a.status==200)try{eval(a.responseText)}catch(b){r()}else r()};a.send(null)}}
function v(a){for(var b=0,c=0,d,e;(d=a[b])&&(e=q[c]);b++,c++)if(google.Toolbelt.pti[c])e.id!=d[0]&&b--;else{if(d[2]){e.className="tbos";google.listen(e,"click",google.Toolbelt.tbosClk)}else e.className="tbou";e.id=d[0];e.innerHTML=d[1]}}function x(a){for(var b=0,c;c=google.Toolbelt.pbt[b++];)if(c[0]==a)return true;return false}
google.Toolbelt.initializeToolElements=function(){p=[];q=[];var a=document.getElementById("tbd");if(a){for(var b=a.getElementsByTagName("ul"),c=0,d;d=b[c++];){p.push(d);d=d.getElementsByTagName("li");for(var e=0,f;f=d[e++];)q.push(f)}}};
function y(){var a=document.getElementById("tbd");if(!a.getAttribute("data-loaded")){a.setAttribute("data-loaded",1);var b=[],c=0;var d='<li style="opacity:0">';for(var e=0,f=google.Toolbelt.atg.length;e<f;++e){var h=google.Toolbelt.atg[e],g=google.style.hasClass(p[e],"tbpd");b.push('<li><ul class="tbt'+(g?" tbpd":"")+'">');for(var n;(n=
google.Toolbelt.pbt[c])&&n[0]==e;c++){for(g=0;g++<n[1];)b.push(d);b.push('<li class="'+q[c].className+'" id='+q[c].id+">"+q[c].innerHTML)}for(g=0;g++<h;)b.push(d);b.push("</ul>")}a.innerHTML=b.join("");google.Toolbelt.initializeToolElements();u()}}
function z(a){for(var b=[],c=[],d=a?0:1,e=a?1:0,f=null,h=0,g;g=p[h];h++){google.style.hasClass(g,"tbpd")||b.push([g,"marginBottom",d*8,e*8]);if(x(h))f=g;}
google.style.hasClass(f,"tbpd")&&b.push([f,"marginBottom",d*8,e*8]);for(h=0;f=q[h];h++)if(!google.Toolbelt.pti[h]){b.push([f,"height",d*1.2,e*1.2,0,"em"]);b.push([f,"paddingBottom",d*3,e*3]);c.push([f,"opacity",d,e,0,""]);f.style.overflow="hidden";}d=a?b:c;var C=a?c:b;google.fx.animate(300,d,function(){document.body.className=
document.body.className.replace(/\btbo\b/,"")+(a?" tbo":"");google.fx.animate(200,C,function(){var s=a?"":"none";for(m=0;i=q[m];m++){if(a){i.style.height=
"";i.style.overflow="visible";i.style.opacity="";}}})})}google.Toolbelt.togglePromotedTools=function(){var a=!google.style.hasClass(document.body,"tbo");a&&y();t(a);z(a);google.log("toolbelt",(a?"0":"1")+"&ei="+google.kEI);return false};
google.rein.push(google.Toolbelt.initializeToolElements);function A(a){for(;a&&!google.hasClass(a,"tbt");)a=a.parentNode;return a}
google.Toolbelt.ctlClk=function(a,b,c){a=a||"cdr_opt";if(a=="cdr_opt"){c&&c.stopPropagation();}google.Toolbelt.maybeLoadCal&&google.Toolbelt.maybeLoadCal();b=b||"cdr_min";if(a=document.getElementById(a)){a.className="tbots";if(a=A(a)){c=0;for(var d;d=a.childNodes[c++];)if(d.className=="tbos")d.className="tbotu";(b=document.getElementById(b))&&
b.focus()}}return false};google.Toolbelt.cdrClk=google.Toolbelt.ctlClk;function B(a){return a.replace(/_/g,"_1").replace(/,/g,"_2").replace(/:/g,"_3")}google.Toolbelt.cdrSbt=function(){return D("ctbs",{cdr_min:"cd_min",cdr_max:"cd_max"})};google.Toolbelt.clSbt=function(){return D("ltbs",{l_in:"cl_loc"})};google.Toolbelt.prcSbt=function(a,b){D("prcbs",{prc_max:b,prc_min:a});var c=document.getElementById("prc_frm");if(c){var d=document.getElementById("tsf");if(d)c.elements.q.value=d.elements.q.value}};
function D(a,b){var c=document.getElementById(a);if(c)for(var d in b){var e=B(document.getElementById(d).value);e=e.replace(/^\s+|\s+$/g,"");var f=RegExp("("+b[d]+":)([^,]*)");c.value=c.value.replace(f,"$1"+e)}return true}google.Toolbelt.tbosClk=function(a){a=a||window.event;if((a=a.target||a.srcElement)&&a.className=="tbotu"){a.className="tbos";if(a=A(a))for(var b=0,c;c=a.childNodes[b++];)if(c.className=="tbots")c.className="tbou"}};})();
if(!window.gbar||!gbar.close){window.gbar={};(function(){var e=window.gbar,i,k,l;function m(a){var b=window.encodeURIComponent&&(document.forms[0].q||"").value;if(b)a.href=a.href.replace(/([?&])q=[^&]*|$/,function(d,c){return(c||"&")+"q="+encodeURIComponent(b)})}e.qs=m;function n(a,b,d,c,f,g){var h=document.getElementById(a);if(h){var j=h.style;j.left=c?"auto":b+"px";j.right=c?b+"px":"auto";j.top=d+"px";j.visibility=k?"hidden":"visible";if(f&&g){j.width=f+"px";j.height=g+"px"}else{n(i,b,d,c,h.offsetWidth,h.offsetHeight);k=k?"":a}}}
e.tg=function(a){a=a||window.event;var b,d=a.target||a.srcElement;a.cancelBubble=true;if(i!=null)o(d);else{b=document.createElement(Array.every||window.createPopup?"iframe":"div");b.frameBorder="0";i=b.id="gbs";b.src="#";document.body.appendChild(b);document.onclick=e.close;o(d);e.alld&&e.alld(function(){var c=document.getElementById("gbli");if(c){var f=c.parentNode;p(f,c);var g=c.prevSibling;f.removeChild(c);e.removeExtraDelimiters(f,g);b.style.height=f.offsetHeight+"px"}})}};
function q(a){var b,d=document.defaultView;if(d&&d.getComputedStyle){if(a=d.getComputedStyle(a,""))b=a.direction}else b=a.currentStyle?a.currentStyle.direction:a.style.direction;return b=="rtl"}
function o(a){var b=0;if(a.className!="gb3")a=a.parentNode;var d=a.getAttribute("aria-owns")||"gbi",c=a.offsetWidth,f=a.offsetTop>20?46:24;if(document.getElementById("tphdr"))f-=3;var g=false;do b+=a.offsetLeft||0;while(a=a.offsetParent);a=(document.documentElement.clientWidth||document.body.clientWidth)-b-c;c=q(document.body);if(d=="gbi"){var h=document.getElementById("gbi");p(h,document.getElementById("gbli")||h.firstChild);if(c){b=a;g=true}}else if(!c){b=a;g=true}k!=d&&e.close();n(d,b,f,g)}
e.close=function(){k&&n(k,0,0)};function r(a,b,d){if(!l){l="gb2";if(e.alld){var c=e.findClassName(a);if(c)l=c}}a.insertBefore(b,d).className=l}function p(a,b){for(var d,c=window.navExtra;c&&(d=c.pop());)r(a,d,b)};
})();;};
if(!window.google)window.google={};window.google.crm={};window.google.cri=0;
window.clk=function(e,f,g,k,l,b,m){if(document.images){var a=encodeURIComponent||escape,c=new Image,h=window.google.cri++;window.google.crm[h]=c;c.onerror=c.onload=c.onabort=function(){delete window.google.crm[h]};var d,i,j;if(google.v6){d=
google.v6.src;i=google.v6.complete||google.v6s?2:1;j=(new Date).getTime()-google.v6t;delete google.v6}if(b&&b.substring(0,6)!="&sig2=")b="&sig2="+b;c.src=["/url?sa=T","&source="+google.sn,"&cd=",a(l),google.j&&google.j.pf?"&sqi=2":"","&ved=",a(m),e?"&url="+a(e.replace(/#.*/,"")).replace(/\+/g,
"%2B"):"","&ei=",google.kEI,d?"&v6u="+a(d)+"&v6s="+i+"&v6t="+j:"",b].join("")}return true};
window.rwt=function(a,f,g,k,l,h,c,m){try{if(a===window)for(a=window.event.srcElement;a;){if(a.href)break;a=a.parentNode}var b=encodeURIComponent||escape,d;d=a.getAttribute("href");var e,
i,j;if(google.v6){e=google.v6.src;i=google.v6.complete||google.v6s?2:1;j=(new Date).getTime()-google.v6t;delete google.v6}if(c&&c.substring(0,6)!="&sig2=")c="&sig2="+c;var n=["/url?sa=t","&source="+google.sn,"&cd=",b(l),google.j&&google.j.pf?"&sqi=2":"","&ved=",b(m),"&url=",b(d).replace(/\+/g,
"%2B"),"&ei=",google.kEI,e?"&v6u="+b(e)+"&v6s="+i+"&v6t="+j:"",h?"&usg="+h:"",c].join("");a.href=n;a.onmousedown=""}catch(o){}return true};
(function(){var b;
google.safeSearchBar={toggle:function(a){if(!google.nossbar){a=a||window.event;a.cancelBubble=true;a.stopPropagation&&a.stopPropagation();if(document.getElementById("ss-box").style.visibility=="visible"){document.getElementById("ss-box").style.visibility="hidden";document.body.removeEventListener?document.body.removeEventListener("click",google.safeSearchBar.toggle,false):document.body.detachEvent("onclick",google.safeSearchBar.toggle);if(b)b.style.visibility="hidden"}else{a=document.getElementById("ss-box");var d=
document.getElementById("ss-status");if(!b){b=document.createElement(Array.every||window.createPopup?"iframe":"div");b.frameBorder="0";b.src="#";a.parentNode.appendChild(b).id="ss-barframe";var c=a.offsetWidth-2;document.getElementById("ss-off").style.width=c+"px";document.getElementById("ss-moderate").style.width=c+"px";document.getElementById("ss-strict").style.width=c+"px"}c=0;do c+=d.offsetLeft;while(d=d.offsetParent);a.style.visibility="visible";b.style.visibility="visible";b.style.width=a.offsetWidth+
"px";b.style.height=a.offsetHeight+"px";b.style.position="absolute";b.style.top=a.offsetTop+"px";google.listen(document.body,"click",google.safeSearchBar.toggle)}}},updateLinkUrl:function(a){for(var d=["ss-off","ss-moderate","ss-strict"],c=0,f;f=d[c++];){var e=document.getElementById(f);if(e){f=e;var g=encodeURIComponent(a);e=[e.href.replace(/([?&])prev=([^&]*)&?/i,"$1").replace(/&$/i,""),"&prev=",g].join("");f.href=e}}}};})();
(function(){var f=true,g=false;google.rt={};var h=[],i,j,l,m,n,o,p,q,r,s,t,u,aa,ba,v,da,w,x;
google.rt.init=function(a,c,b){i=30;j=[];m=l=g;n="";p=0;q=g;r=(new Date).getTime();s=100;t=0;u=g;w=[];x="";if(o=document.getElementById(a)){if(b){if(b.maxResults)s=b.maxResults;if(b.promotedTweetRequestUrl)x=b.promotedTweetRequestUrl}b=function(){q=f};google.listen(document,"keydown",b);google.listen(document,"mousemove",b);c&&ea(c);t+=o.getElementsByTagName("li").length;j.length==0&&window.setTimeout(y,3E3);google.rt.timestampToString=fa;ga(o,w);ha(o,w);z(y,i);if(ia("sbu","sbd","sbb",a)){A.push(function(){m=
f});B.push(function(){m=g});C(0,f)}ja(ka,3E3,6E3);la()}};google.rt.pause=function(){window.clearTimeout(v);D();var a=document.getElementById("rth").getElementsByTagName("span");E(a[0]);a[1].style.display="";da=(new Date).getTime()};google.rt.resume=function(){if(((new Date).getTime()-da)/1E3>10)j=[];y();z(y,i);ja(ka,2E3,6E3);var a=document.getElementById("rth").getElementsByTagName("span");E(a[1]);a[0].style.display=""};function E(a){a.style.display="none"}
function ma(a){return Math.min(7200,(Math.random()+0.5)*Math.pow(2,a)*5)}function z(a,c){var b=c;if(p)b=ma(p);v=window.setTimeout(function(){a();z(a,c)},b*1E3)}function ja(a,c,b){aa=window.setTimeout(function(){a();ba=window.setInterval(a,b)},c)}function D(){window.clearTimeout(aa);window.clearInterval(ba)}
function ka(){if(!j.length||m){if(u){D();var a=document.getElementById("rth").getElementsByTagName("span");if(a.length>2){E(a[0]);E(a[1]);a[2].style.display=""}}}else{var c=j.shift();a=c.e;var b=a.getElementsByTagName("li")[0];o.insertBefore(a,o.firstChild);c.updateDate();google.History.save(na,{r:o.innerHTML,u:n,n:t,s:w,t:F()});var d;d=-google.getComputedStyle(b,"height")-google.getComputedStyle(b,"margin-bottom");c=o.scrollTop;if(c<20){C(c);google.fx.animate(1200,[[a,"marginTop",d,0,google.fx.easeInAndOut]])}else C(c-d)}}function ea(a){if(a.results){var c=a.results.length;t+=c;for(var b=0;b<h.length;++b)h[b](a.results);for(b=c;c=a.results[--b];)j.push(oa(c))}if(a.nextRequest)n=a.nextRequest;if(a.pollSeconds)i=a.pollSeconds}google.rt.pushRealtimeResultsCallback=function(a){h.push(a)};
window.mbrt0=window.a={insert:function(a){a=eval("("+a+")");"numUpdates"in a?pa(a):ea(a)}};function y(){if(q){q=g;r=(new Date).getTime()}else if((new Date).getTime()-r>24E4)return;u=t+5>s;if(!(l||u||!n)){var a=google.xhr();a.open("GET",n);a.onreadystatechange=function(){if(a.readyState==4){if(a.status==200){eval(a.responseText);p=0}else p++;l=g}};l=f;a.send(null)}}
window.mbrtpl={insert:function(a){a=eval("("+a+")");if(a.results){var c=a.results.length,b=document.getElementById("rtpl");if(b&&c>0){c=c;for(var d;d=a.results[--c];)b.innerHTML+=d.html;b.style.display=""}}}};function la(){if(x){var a=google.xhr();a.open("GET",x);a.onreadystatechange=function(){a.readyState==4&&a.status==200&&eval(a.responseText)};a.send(null)}}function oa(a){var c=document.createElement("div");c.innerHTML=a.html;return{e:c,updateDate:qa(c,w)}}
var na=google.History.client(function(a){o.innerHTML=a.r;n=a.u;t=a.n;w=a.s;G(o,w,a.t);C(0,f);j=[];y()});google.dstr.push(function(){D();window.clearTimeout(v)});var H,I,J,K,L,M,N,A,B,O,P,Q=g;function R(a){var c;c=google.getComputedStyle(a,"height");return c}function S(a){a=a.offsetTop;a-=K.offsetTop;return a}
function T(a){if(a)for(var c=0,b;b=A[c++];)b();else if(N)for(c=0;b=B[c++];)b();N=a}function U(a){var c=ra(a);if(c){var b=S(c);a||(b+=R(c)-P);sa(b,f,300,function(){ta(a)})}}function sa(a,c,b,d){var e=K.scrollHeight-P;e=e==0?0:ua(a*(O-Math.max(P/K.scrollHeight*O,20))/e);e=[[J,"marginTop",google.getComputedStyle(J,"margin-top"),e,google.fx.easeInAndOut]];if(c)e.push([K,"scrollTop",K.scrollTop,a,google.fx.easeInAndOut,""]);else K.scrollTop=a;google.fx.animate(b,e,d)}
function ta(a){setTimeout(function(){N&&U(a)},200)}function ra(a){var c=K.childNodes;if(a)for(a=c.length-1;a>=0;--a){var b=c[a],d=S(b);if(b.nodeType==1&&d<K.scrollTop)return b}else for(a=0;b=c[a++];){d=S(b);if(b.nodeType==1&&d+R(b)>K.scrollTop+P)return b}}function va(a){var c=a.clientY-L;c=ua(google.getComputedStyle(J,"margin-top")+c);J.style.marginTop=c+"px";K.scrollTop=c*(K.scrollHeight-P)/(O-R(J));L=a.clientY}function ua(a){return Math.max(0,Math.min(O-R(J),a))}
function C(a,c){if(Q){var b=R(J),d=Math.max(P/K.scrollHeight*O,20),e=document.getElementById("sbbb");b=[[J,"height",b,d],[e,"marginTop",b-7,d-7]];if(!M){e=d=0;for(var k;k=K.childNodes[e++];)if(k.nodeType==1)d+=R(k);if(d>P){b.push([document.getElementById("sb"),"opacity",0,1,google.fx.linear,""]);M=f}}d=c?0:1200;sa(a,g,d);google.fx.animate(d,b,function(){if(M)J.style.position="absolute"})}}
function V(a,c){if(a.parentNode==J)a=J;var b=70*(c?1:-1);wa(a,b);for(var d=0,e;e=a.childNodes[d++];)e.nodeType==1&&wa(e,b)}function wa(a,c){var b=a.style.backgroundPosition.match(/^-?\d+/),d=a.style.backgroundPosition.match(/\s+.*$/);a.style.backgroundPosition=parseInt(b,10)+c+"px "+(d?d:"")}
function ia(a,c,b,d){H=document.getElementById(a);I=document.getElementById(c);J=document.getElementById(b);K=document.getElementById(d);if(!(H&&I&&J&&K))return Q=g;N=M=g;A=[];B=[];O=google.getComputedStyle(document.getElementById("sbc"),"height")-1;P=google.getComputedStyle(K,"height");a=[H,I,J];for(c=0;b=a[c++];){google.listen(b,"mouseover",function(e){V(e.target)});google.listen(b,"mouseout",function(e){V(e.target,f)});b.onmousedown=function(){return g};
}google.listen(H,"mousedown",function(){T(f);U(f)});google.listen(I,"mousedown",function(){T(f);U()});google.listen(J,"mousedown",function(e){T(f);L=e.clientY;google.listen(document,"mousemove",va)});return Q=f}
google.listen(document,"mouseup",function(){document.removeEventListener("mousemove",va,g);T(g)});google.dstr.push(function(){A=B=[];Q=g});google.rt||(google.rt={});var xa=-1;google.rt.timestampToString=null;function ya(a,c){for(var b=a.getElementsByTagName("div"),d=0,e;e=b[d++];)if(e.className=="rtdelta"){b=parseInt(e.innerHTML,10);return c-b}return g}function F(){return Math.round((new Date).getTime()/1E3)}
function fa(a,c){var b=c-a;if(b<86400)return b<45?"seconds ago":b<105?"1 minute ago":b<3345?"1 minutes ago".replace("1",Math.floor(b/60)+(b%60>=45?1:0)+""):b<6600?"1 hour ago":"1 hours ago".replace("1",Math.floor(b/3600)+(b%3600>=3E3?1:0)+"");return g}function za(a){var c=[];a=a.getElementsByTagName("span");for(var b=0,d;d=a[b++];)d.className.match("rtd")&&c.push(d);return c}
function G(a,c,b){a=za(a);b=b||F();for(var d=0,e;e=a[d];d++){e=e;var k=c[d];if(k)if(k=(0,google.rt.timestampToString)(k,b))e.innerHTML=k}}function qa(a,c,b){var d=b||F();return function(){var e;e=za(a);e=e.length>0?e[0]:g;if(e){var k=ya(e,d);if(k){var ca=F();if(k)if(ca=(0,google.rt.timestampToString)(k,ca))e.innerHTML=ca;c.unshift(k)}}}}function ga(a,c,b){a=za(a);b=b||F();for(var d=0,e;e=a[d++];)(e=ya(e,b))&&c.push(e)}
function ha(a,c){xa=window.setInterval(function(){G(a,c)},6E4);google.dstr.push(function(){window.clearInterval(xa)})};google.rt.replayCallbacks=[];google.rt.pushReplayCallback=function(a){google.rt.replayCallbacks.push(a)};function Aa(){google.rt.timestampToString=function(a){return google.rt.formatTime(a,"FullDate")}}google.rt.replayinit=function(a){o=document.getElementById(a);w=[];Aa();if(o){google.rt.pushReplayCallback(function(){ga(o,w,null);G(o,w)});google.History.save(na,{r:o.innerHTML,s:w,t:F()})}};google.rtc={};var Ba,Ca,W,X,Da,Ea,Y,Fa,Ga,Z,$;google.rtc.init=function(a,c){var b;if(b=c)if(Ba=document.getElementById(a)){Ca=parseInt(Ba.innerHTML,10);W=0;Ea="";Y=g;Fa=(new Date).getTime();Z=Ga=0;$=g;Da=X=0;b=f}else b=g;if(b){pa(c);b=function(){Y=f};google.listen(document,"keydown",b);google.listen(document,"mousemove",b);Ha(Ia,1)}};
function Ha(a,c){if(Y){Y=g;Fa=(new Date).getTime()}if(!(Ga>200||Z>3||(new Date).getTime()>Fa+24E4)){Ja();var b=c;if(Z)b=ma(Z);var d;if($||W!=0)d=function(){Ha(a,c)};else{X=0;d=function(){a();Ha(a,c)}}window.setTimeout(d,b*1E3)}}function Ia(){var a=google.xhr();a.open("GET",Ea);a.onreadystatechange=function(){if(a.readyState==4)if(a.status==200){eval(a.responseText);Z=0}else Z++;$=g};$=f;a.send(null)}function pa(a){if(a.numUpdates)X=a.numUpdates;if(a.nextRequest)Ea=a.nextRequest}
function Ja(){if(!$){Ga++;W++;if(W>=30)W-=30;var a=Da+X/30,c=Math.round(a);Da=a-c;Ca+=c;Ba.innerHTML=Ca}};})();
(function(){var e=false;function h(a){google.srp.updateLinksWithParam("prmdo",a?"1":"",google.srp.isSerpLink,google.srp.isSerpForm)}function i(a,c,b){return[[c,"height",a?b:0,a?0:b],[c,"opacity",a?1:0,a?0:1,null,""]]}function j(a){if(!a)return null;var c=a.offsetHeight,b=google.style.getComputedStyle(a,"overflow",1);a.style.overflow="hidden";return{height:c,overflow:b}}
function l(a,c,b){if(c)a.style.height=b.height+"px";else a.style.removeAttribute&&a.style.removeAttribute("filter");a.style.overflow=b.overflow}
google.srp.toggleModes=function(){if(!e){e=true;var a=document.getElementById("ms"),c=document.getElementById("hidden_modes"),b=document.getElementById("hmp"),d=google.style.hasClass(a,"open");a.className="open";var k=j(c),f=j(b),g=i(d,c,k.height);if(f)g=g.concat(i(d,b,f.height));h(!d);google.fx.animate(227,g,function(){if(d)a.className="";l(c,d,k);b&&l(b,d,f);e=false})}};})();
(function(){google.tbpr={};var d={},g=/\bl\b/,h=function(b){return g.test(b.className)},i=function(b){var c="",a;for(a in d)d[a].style.display="none";if(b.a>=0){c=b.a;if(d[c])d[c].style.display="block";c="tbpr:idx="+b.a}return c},j=function(b,c){c.a=b.b||-1};
google.tbpr.init=function(){for(var b=document.getElementsByTagName("h3"),c=0,a;a=b[c++];)if(a.className=="tbpr"){var e=Number(a.id.substr(5));a=d[e]=a;for(e=e;a&&a.nodeName!="LI";)a=a.parentNode;if(a){a=a.getElementsByTagName("a");for(var k=0,f=void 0;f=a[k++];)if(h(f)){f.b=e;break}}}google.event.back.init();google.event.back.register(h,j,i,"tbpr")};})();
(function(){function c(a){var b="inner"+a;a="client"+a;if(window[b])return window[b];else if(document.documentElement&&document.documentElement[a])return document.documentElement[a];return 0}function e(){f("biw",c("Width"));f("bih",c("Height"))}function f(a,b){for(var d=document.getElementsByName(a),i=0,g;g=d[i++];)g.value=b}
function h(a){a=a||window.event;for(a=a.target||a.srcElement;a&&a.tagName!="A";)a=a.parentNode;if(a&&a.href&&a.href.indexOf("/images?")!=-1){var b=j(a.href,"biw",c("Width"));a.href=j(b,"bih",c("Height"))}}function j(a,b,d){return a.replace(RegExp("([?&#])"+b+"=([^&#]*)&?","i"),"$1").replace(/&*(#|$)/,"&"+b+"="+d+"$1")}google.y.first.push(function(){if(location.href.indexOf("/images?")==-1){e();google.listen(window,"resize",e)}google.listen(document,"click",h)});})();
(function(){var c=true,d=false,g,h,i=c,j,k,l=["position","top","left","zIndex","margin","width"],n={},p={};function q(a){if(google.browser.engine.IE)return document.documentElement["client"+a];return window["inner"+a]}function r(){if(j){p.ot=google.style.getPageOffsetTop(j);p.ol=google.style.getPageOffsetLeft(j);p.iw=google.style.getWidth(j);p.ow=j.offsetWidth;p.oh=j.offsetHeight;for(var a=0,b;b=l[a++];)n[b]=j.style[b]}}function s(){if(j)for(var a in n)j.style[a]=n[a]}
function t(){var a=document.getElementById("rhs_map-placeholder");a&&a.parentNode.removeChild(a)}
function u(){if(j){if(google.style.getComputedStyle(j,"position",c)!="absolute"){var a=document.createElement("div");a.id=j.id+"-placeholder";if(google.browser.engine.IE)a.style.styleFloat=google.style.getComputedStyle(j,"styleFloat",c);else a.style.cssFloat=google.style.getComputedStyle(j,"float",c);a.style.width=p.ow+"px";a.style.height=p.oh+"px";a.style.marginTop=google.style.getComputedStyle(j,"margin-top",c);a.style.marginBottom=google.style.getComputedStyle(j,"margin-bottom",c);a.style.marginLeft=
google.style.getComputedStyle(j,"margin-left",c);a.style.marginRight=google.style.getComputedStyle(j,"margin-right",c);j.parentNode.insertBefore(a,j.nextSibling)}j.style.margin=0;j.style.zIndex=1500;j.style.width=p.iw+"px";j.style.top=p.ot-g+"px";j.style.left=p.ol+1+"px";j.style.position="fixed"}}function v(){r();u();h=c}function w(){t();s();h=d}function x(){if(i){var a=document.body.scrollTop+document.documentElement.scrollTop;if(!h&&a>=g)v();else h&&a<g&&w()}}
function y(){if(!j)return d;var a=document.getElementById("rhs_block");if(!a)return d;var b=a.getElementsByTagName("li");if(!b||b.length==0)return d;a=q("Height");var e=document.getElementById("leftnav");e=google.style.getPageOffsetTop(e)+google.style.getHeight(e);var f=google.style.getHeight(j);b=b[0].offsetHeight+12;b=2*b+f+google.style.getPageOffsetTop(j);return a<Math.max(b,e)}function z(){h&&w();if(y())i=d;else{i=c;g=google.style.getPageOffsetTop(document.getElementById("leftnav"));x()}}var A;
function B(){this.m=google.getHeight(j);this.h=q("Height");this.w=q("Width");this.isStateEqual=function(a){if(google.browser.engine.IE)return this.b==a.b&&this.h==a.h&&this.w==a.w;return this.h==a.h}}function C(){var a=new B;if(!a.isStateEqual(A)){z();A=a}}
function D(){if(google.listen&&google.style.getHeight){j=document.getElementById("rhs_map");n={};p={};A=new B;google.listen(window,"scroll",x);if(google.browser.engine.IE)k=window.setInterval(C,200);else google.listen(window,"resize",z);z()}else window.setTimeout(function(){D()},100)}function E(){google.unlisten(window,"scroll",x);google.browser.engine.IE||google.unlisten(window,"resize",z);k&&window.clearInterval(k);j=null}
function F(){if(!(google.browser.engine.IE&&google.browser.compareVersions("7",google.browser.product.version)==0)&&!google.browser.product.IPAD)document.getElementById("tbt5")||document.getElementById("rhs_map")&&D()};google.LU={};var G,H=[],I,J,K,L,M,N,O,P,Q,R;google.LU.featureMap=function(a){if((H=a)&&H.length>0)S();else H=[]};function T(a){for(var b=0,e;b<H.length;++b)if(e=H[b].features)for(var f=0,m;m=e[f];++f)if(!a(m))return}function U(){Q=I.offsetWidth;R=I.offsetHeight}
function S(){google.listen(I,"mousemove",V);var a=H[0].rectangle;if(a&&a.length==4){N=a[2]-a[0];O=a[3]-a[1]}P=I.style.background.indexOf("center")!=-1||I.style.background.indexOf("50% 50%")!=-1;google.log("lu_featuremap",google.time()-G+"")}function W(a){var b=O/R;a={x:a.x*b,y:a.y*b};if(P)a.x+=(N-Q*b)/2;return a}var X=0;
function V(a){var b=google.time();if(!(b-X<100)){X=b;U();a={x:(a||window.event).clientX+document.body.scrollLeft+document.documentElement.scrollLeft-google.style.getPageOffsetLeft(I),y:(a||window.event).clientY+document.body.scrollTop+document.documentElement.scrollTop-google.style.getPageOffsetTop(I)};a=W(a);a=Y(a.x,a.y);J.href=L;if(a){a=a.id;J.style.cursor="pointer";if(!M&&a!="0")J.href+="&iwloc="+a}else J.style.cursor="default"}}
function Y(a,b){if(H.length==0)return null;var e=null;T(function(f){var m=a-f.a[0],o=b-f.a[1];if(m>=f.bb[0]&&o>=f.bb[1]&&m<=f.bb[2]&&o<=f.bb[3]){e=f;return d}return c});return e}google.LU.init=function(){document.getElementById("rhs_map")&&F();var a=window.google.LU.fmap_url_delta;a&&Z(a)};
function Z(a){if(I=document.getElementById("lu_map")){for(J=I;J&&J.tagName!="A";)J=J.parentNode;var b=document.getElementById("rhs_map");if(b)K=b;else for(K=J;K&&(K.tagName!="LI"||google.style.hasClass("g"));)K=K.parentNode;if(J&&K){L=J.href;M=L.indexOf("&iwloc=")!=-1||L.indexOf("&cid=0,0,")!=-1;if(I.tagName=="IMG")b=I.src;else{b=/url\(([\'\"]?)(.*)\1\)/.exec(I.style.background);if(!b||b.size<3)return;b=b[2]}var e=/\/vt\/data=[^,]+,[^,]+$/;if(e.test(b)){e=b.indexOf("data=");var f=b.indexOf(","),m=
b.substring(0,e+5)+a+b.substr(f)+"&callback=google.LU.featureMap";K.fetchOnce=c;K.fetch=function(){if(K.fetchOnce){K.fetchOnce=d;G=google.time();google.unlisten(K,"mouseover",K.fetch);var o=document.createElement("SCRIPT");o.src=m;google.append(o)}};google.listen(K,"mouseover",K.fetch)}}}}function $(){I&&google.unlisten(I,"mousemove",V);document.getElementById("rhs_map")&&E();j=null;H.length=0}google.register(84,{init:google.LU.init,dispose:$});})();
(function(){var d=true,e=false;var f,g=window.google.j,i=null,k=e,l=d,m=0,n={_s:{},_stt:{},_t:{}},o=function(a){return f=a},p=function(a,b){var c=b.match("[&?#]"+a+"=([^&]*)");return c?c[1]||"":null},r=function(a,b,c){c||(m=0);if(f&&a.indexOf("&fp=")==-1){b||(f=undefined);return d}if(!g||!g.ckc)return d;if((a=q(a))&&!b)f=undefined;return a},s=function(a){a.indexOf("&pf=")!=-1&&google.log("1",["1&sqi=3&ei=",google.kEI,"&q=",p("q",a)].join(""));return d},t=function(a){if(!l)return a;var b=a;g&&g.hsa(document.gs||document.f,e,e,d);
var c=google.jesrstate;if(!c)return a;var h;h=(h=p("tbs",c))?!!i&&i.test(h):d;if(!h)return a;a=a.replace("/complete/search","/s");a=a.replace(/([&\?])client=([^&]*)/,"$1sclient=$2");c=c.substring(1);h=[a,"pf=i"];c=c.split("&");for(var j=0;j<c.length;++j){var w=c[j].split("=");a.search("[&^]"+w[0]+"=")==-1&&h.push(c[j])}a=h.join("&");if(n._t()==4){n._s(a);return b}else return a},u=function(a){if(l){l=e;a=["1&dpf=",a,"&ei=",google.kEI,"&expid=",google.kEXPI].join("");google.log("1",a);g&&g.sjcv&&g.sjcv({sendSlowCSI:d})}},
v=function(a,b){if(a==2&&b==15){u("s");try{if(window.localStorage&&!window.localStorage.readonly)window.localStorage["web-ig-sc"]=google.time()+""}catch(c){}g.sjcv&&g.sjcv({csiSlowMarker:2})}else a==1&&++m>=3&&u("e");return e},q=function(a){var b=g.ckc;a=b(a,{safe:1,fp:1});b=b(f,{safe:1,fp:1});return a==b},x=function(a,b){if(a==7&&q(b))return 2;return 1},y=function(a,b,c){if(typeof c=="string"){if(!q(c))return 1;if(b==21||b==0||b==1||b==12||b==9)return 2}return 1},z=function(a){a=a||window.event;
a.cancelBubble=d;a.stopPropagation&&a.stopPropagation();a=google.dom.get("#po-box").style;if(a.display=="none"){a.display="";google.listen(document.body,"click",z)}else{a.display="none";google.unlisten(document.body,"click",z)}},A=function(){if(!window.localStorage)return e;var a=window.localStorage.getItem("web-ig-sc");if(!a)return e;if(typeof a.value=="string")a=a.value;a=parseInt(a,10);var b=google.time();if(a>0&&b-a<864E5)return d;window.localStorage.removeItem("web-ig-sc");return e},B=function(a){if(!k){google.psy=
{t:z};if(g&&g.init){if(a&&a.mds)i=RegExp("^(?:(?:"+a.mds+"):[^,]+(?:,|$))*$");google.msg.listen(0,s,1,r,5,o,30,x,25,y,16,t,17,v);var b=window.google.ac;b&&b.sv&&b.sv({addPbx:d});b&&b.uhi&&b.uhi();var c=window.location.href.indexOf("#");if(c!=-1)f="/search?"+window.location.href.substring(c+1);if(g&&g.gt){(n=g.gt())&&b&&b.st&&b.st(n);if(n&&n._stt&&a)n._stt([a.avgTtfc||0,a.avgTtlc||0,a.avgCbt||0],[a.maxTtfc||0,a.maxTtlc||0,a.maxCbt||0])}if((a=a&&a.optOut)||A()){u(a?"n":"s");if(g.sjcv)g.sjcv({csiSlowMarker:a?
1:2})}k=d}}};google.register(92,{init:B,jesrLoaded:B});})();
(function(){if(google.y.first){for(var a=0,b;b=google.y.first[a];++a)b();delete google.y.first}for(a in google.y)google.y[a][1]?google.y[a][1].apply(google.y[a][0]):google.y[a][0].go();google.y.x=google.x;google.x=function(d,c){c&&c.apply(d);return false};google.y.first=[];})();
(function(){if(window.google){window.google.a={};window.google.c=1;var j=function(a,b,e){b=a.t[b];a=a.t.start;if(b&&(a||e)){if(e!=undefined)a=e;return b>a?b-a:a-b}},k=function(a,b,e){var d="";if(window.google.pt){d+="&srt="+window.google.pt;delete window.google.pt}var c=document.getElementById("csi");if(c){var f;if(window.google._bfr!=undefined)f=window.google._bfr;else{f=c.value;window.google._bfr=f;c.value=1}if(f)return""}if(c=window.chrome)if(c=c.loadTimes){if(c().wasFetchedViaSpdy)d+="&p=s";if(c().wasNpnNegotiated)d+=
"&npn=1";if(c().wasAlternateProtocolAvailable)d+="&apa=1"}if(a.b)d+="&"+a.b;if(window.parent!=window)d+="&wif=1";c=a.t;f=c.start;var h=[],g;for(g in c)g!="start"&&f&&h.push(g+"."+j(a,g));delete c.start;if(b)for(var i in b)d+="&"+i+"="+b[i];return a=[e?e:"/csi","?v=3","&s="+(window.google.sn||"GWS")+"&action=",a.name,"",d,"&rt=",h.join(",")].join("")};window.google.report=function(a,b,e){a=k(a,b,e);if(!a)return"";b=new Image;var d=window.google.c++;window.google.a[d]=b;b.onload=b.onerror=function(){delete window.google.a[d]};
b.src=a;b=null;return a}};function l(){function a(c){try{var f=window.external[c];if(f!=undefined){google.kCSI[c]=f;return true}}catch(h){}return false}for(var b=["ist_rc","ist_rn","ist_nr","ist_cdts","ist_dp","ist_rrx","ist_rxr","ist_rs","ist_sr"],e=0,d;d=b[e++];)if(a(d)===false)break}
if(google.timers&&google.timers.load.t){if(!google.nocsixjs)google.timers.load.t.xjsee=google.time();window.setTimeout(function(){if(google.timers.load.t){google.timers.load.t.xjs=google.time();l();google.timers.load.t.ol&&google.report(google.timers.load,google.kCSI)}},0)};})();
